// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'base.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CharacterCastePrivilege _$CharacterCastePrivilegeFromJson(
  Map<String, dynamic> json,
) => CharacterCastePrivilege(
  privilege: $enumDecode(_$CastePrivilegeEnumMap, json['privilege']),
  description: json['description'] as String?,
);

Map<String, dynamic> _$CharacterCastePrivilegeToJson(
  CharacterCastePrivilege instance,
) => <String, dynamic>{
  'privilege': _$CastePrivilegeEnumMap[instance.privilege]!,
  'description': instance.description,
};

const _$CastePrivilegeEnumMap = {
  CastePrivilege.apprenti: 'apprenti',
  CastePrivilege.autorisation: 'autorisation',
  CastePrivilege.charteDAtelier: 'charteDAtelier',
  CastePrivilege.ecole: 'ecole',
  CastePrivilege.elementalisme: 'elementalisme',
  CastePrivilege.familier: 'familier',
  CastePrivilege.notable: 'notable',
  CastePrivilege.outils: 'outils',
  CastePrivilege.psychometrie: 'psychometrie',
  CastePrivilege.reparationDeRoutine: 'reparationDeRoutine',
  CastePrivilege.symbiose3: 'symbiose3',
  CastePrivilege.symbiose5: 'symbiose5',
  CastePrivilege.symbiose8: 'symbiose8',
  CastePrivilege.expertiseArtisan: 'expertiseArtisan',
  CastePrivilege.faveurPolitiqueArtisan: 'faveurPolitiqueArtisan',
  CastePrivilege.tuteurArtisan: 'tuteurArtisan',
  CastePrivilege.adaptation: 'adaptation',
  CastePrivilege.anticipation: 'anticipation',
  CastePrivilege.argotCombattant: 'argotCombattant',
  CastePrivilege.botteSecrete: 'botteSecrete',
  CastePrivilege.convictionSuperieure: 'convictionSuperieure',
  CastePrivilege.doubleAttaque: 'doubleAttaque',
  CastePrivilege.engagement: 'engagement',
  CastePrivilege.feinte: 'feinte',
  CastePrivilege.recuperation: 'recuperation',
  CastePrivilege.riposte: 'riposte',
  CastePrivilege.sommeilLeger: 'sommeilLeger',
  CastePrivilege.vigilanceCombattant: 'vigilanceCombattant',
  CastePrivilege.alliesMercenairesCombattant: 'alliesMercenairesCombattant',
  CastePrivilege.compagnonsDeBatailleCombattant:
      'compagnonsDeBatailleCombattant',
  CastePrivilege.maitriseDArmureCombattant: 'maitriseDArmureCombattant',
  CastePrivilege.bonneFoi: 'bonneFoi',
  CastePrivilege.bonneFortune: 'bonneFortune',
  CastePrivilege.expertise: 'expertise',
  CastePrivilege.faveurPolitique: 'faveurPolitique',
  CastePrivilege.fournisseurDePoisons: 'fournisseurDePoisons',
  CastePrivilege.notorieteCommercant: 'notorieteCommercant',
  CastePrivilege.psychologie: 'psychologie',
  CastePrivilege.reflexesDeFuite: 'reflexesDeFuite',
  CastePrivilege.reseau: 'reseau',
  CastePrivilege.ressources: 'ressources',
  CastePrivilege.rumeurs: 'rumeurs',
  CastePrivilege.connaissanceDuMondeCommercant: 'connaissanceDuMondeCommercant',
  CastePrivilege.messagerCommercant: 'messagerCommercant',
  CastePrivilege.relationsDAffairesCommercant: 'relationsDAffairesCommercant',
  CastePrivilege.ambassade: 'ambassade',
  CastePrivilege.aplomb: 'aplomb',
  CastePrivilege.avalDraconique: 'avalDraconique',
  CastePrivilege.calligraphieOfficielle: 'calligraphieOfficielle',
  CastePrivilege.demagogie: 'demagogie',
  CastePrivilege.ecritTechnique: 'ecritTechnique',
  CastePrivilege.garantErudit: 'garantErudit',
  CastePrivilege.linguistique: 'linguistique',
  CastePrivilege.memoire: 'memoire',
  CastePrivilege.notorieteErudit: 'notorieteErudit',
  CastePrivilege.faveurPolitiqueErudit: 'faveurPolitiqueErudit',
  CastePrivilege.messagerErudit: 'messagerErudit',
  CastePrivilege.psychologieErudit: 'psychologieErudit',
  CastePrivilege.aura: 'aura',
  CastePrivilege.anonymat: 'anonymat',
  CastePrivilege.empathieElementaire: 'empathieElementaire',
  CastePrivilege.laboratoire: 'laboratoire',
  CastePrivilege.leurre: 'leurre',
  CastePrivilege.messager: 'messager',
  CastePrivilege.predispositions: 'predispositions',
  CastePrivilege.prevoyance: 'prevoyance',
  CastePrivilege.sortilegeFetiche: 'sortilegeFetiche',
  CastePrivilege.style: 'style',
  CastePrivilege.tuteur: 'tuteur',
  CastePrivilege.apprentiMage: 'apprentiMage',
  CastePrivilege.engagementMage: 'engagementMage',
  CastePrivilege.memoireMage: 'memoireMage',
  CastePrivilege.donDeBrorne: 'donDeBrorne',
  CastePrivilege.donDeHeyra: 'donDeHeyra',
  CastePrivilege.donDeKali: 'donDeKali',
  CastePrivilege.donDeKalimsshar: 'donDeKalimsshar',
  CastePrivilege.donDeKezyr: 'donDeKezyr',
  CastePrivilege.donDeKhy: 'donDeKhy',
  CastePrivilege.donDeKhymera: 'donDeKhymera',
  CastePrivilege.donDeKroryn: 'donDeKroryn',
  CastePrivilege.donDeMoryagorn: 'donDeMoryagorn',
  CastePrivilege.donDeNenya: 'donDeNenya',
  CastePrivilege.donDOzyr: 'donDOzyr',
  CastePrivilege.donDeSolyr: 'donDeSolyr',
  CastePrivilege.donDeSzyl: 'donDeSzyl',
  CastePrivilege.aplombProdige: 'aplombProdige',
  CastePrivilege.engagementProdige: 'engagementProdige',
  CastePrivilege.reflexesDeDegagement: 'reflexesDeDegagement',
  CastePrivilege.adopte: 'adopte',
  CastePrivilege.autorite: 'autorite',
  CastePrivilege.cuirasse: 'cuirasse',
  CastePrivilege.defense: 'defense',
  CastePrivilege.influences: 'influences',
  CastePrivilege.lucidite: 'lucidite',
  CastePrivilege.porteParole: 'porteParole',
  CastePrivilege.renseignement: 'renseignement',
  CastePrivilege.requisition: 'requisition',
  CastePrivilege.signesDeBatailleProtecteur: 'signesDeBatailleProtecteur',
  CastePrivilege.suspicion: 'suspicion',
  CastePrivilege.engagementProtecteur: 'engagementProtecteur',
  CastePrivilege.notorieteProtecteur: 'notorieteProtecteur',
  CastePrivilege.archer: 'archer',
  CastePrivilege.chasseur: 'chasseur',
  CastePrivilege.compagnons: 'compagnons',
  CastePrivilege.connaissanceDuMonde: 'connaissanceDuMonde',
  CastePrivilege.filsDeLaTerre: 'filsDeLaTerre',
  CastePrivilege.garantVoyageur: 'garantVoyageur',
  CastePrivilege.logistique: 'logistique',
  CastePrivilege.maitriseDArmure: 'maitriseDArmure',
  CastePrivilege.rancune: 'rancune',
  CastePrivilege.solitaire: 'solitaire',
  CastePrivilege.vigilanceVoyageur: 'vigilanceVoyageur',
  CastePrivilege.ambassadeVoyageur: 'ambassadeVoyageur',
  CastePrivilege.familierVoyageur: 'familierVoyageur',
  CastePrivilege.linguistiqueVoyageur: 'linguistiqueVoyageur',
};

AttributeBasedCalculator _$AttributeBasedCalculatorFromJson(
  Map<String, dynamic> json,
) => AttributeBasedCalculator(
  static: (json['static'] as num).toDouble(),
  multiply: (json['multiply'] as num).toInt(),
  add: (json['add'] as num).toInt(),
  dice: (json['dice'] as num).toInt(),
);

Map<String, dynamic> _$AttributeBasedCalculatorToJson(
  AttributeBasedCalculator instance,
) => <String, dynamic>{
  'static': instance.static,
  'multiply': instance.multiply,
  'add': instance.add,
  'dice': instance.dice,
};
