import '../caste/base.dart';
import 'skill_family.dart';

enum Skill {
  // Combat
  armesArticulees(title: "Armes articulées", family: SkillFamily.combat, description: "Permet de connaître et de manier toutes les armes asymétriques à chaîne, souvent composées, comme les fléaux, boulet et les fouets.\nExemples de Spécialisation : par arme."),
  armesContondantes(title: "Armes contondantes", family: SkillFamily.combat, description: "Permet de connaître et de manier les armes dépourvues de lames, telles que masses, bâtons, marteaux etc.\nExemples de Spécialisation : par arme."),
  armesDeChoc(title: "Armes de choc", family: SkillFamily.combat, description: "Permet de connaître et de manier les armes à manche et à fer lourds telles que les haches ou les pics de guerre.\nExemples de Spécialisation : par arme."),
  armesDeJet(title: "Armes de jet", family: SkillFamily.combat, description: "Permet de connaître et de manier les armes de lancer (dagues, fléchettes, etc.). Tous les jets de lancer s'effectuent avec l'attribut Physique.\nExemples de Spécialisation : par arme."),
  armesDoubles(title: "Armes doubles", family: SkillFamily.combat, reservedCastes: [Caste.combattant, Caste.protecteur, Caste.prodige], description: "Permet de connaître et de manier les armes composées de deux armes différentes, telles que le bâton shaaduk't des Prodiges, les double lames.\nCette Compétence est réservée aux combattants, aux protecteurs et aux Prodiges.\nExemples de Spécialisation : par arme."),
  armesDHast(title: "Armes d'hast", family: SkillFamily.combat, description: "Permet de connaître et de manier les armes à hampe longue maniées à deux mains, telles que les piques, les lances de fantassin, les hallebardes, etc.\nExemples de Spécialisation : par arme."),
  armesTranchantes(title: "Armes tranchantes", family: SkillFamily.combat, description: "Permet de connaître et de manier les armes munies de lames telles que les épées, les sabres, etc.\nExemples de Spécialisation : par arme."),
  bouclier(title: "Bouclier", family: SkillFamily.combat, description: "Permet de manier efficacement les différents types de bouclier, en défense comme en attaque. Seuls les protecteurs peuvent utiliser le bouclier dragon, qui est l'apanage de leur caste.\nExemples de Spécialisation : par type de bouclier."),
  corpsACorps(title: "Corps à corps", family: SkillFamily.combat, description: "Permet de se battre en utilisant ses poings, ses pieds et sa tête, ainsi que de manier des armes de poing telles que les poignards, les gants de combat, etc.\nExemples de Spécialisation : par arme ou coup de poing, coup de pied, etc."),
  criDeLaPierre(title: "Cri de la Pierre", family: SkillFamily.combat, reservedCastes: [Caste.mage], description: "Cette Compétence est uniquement accessible aux Mages de la Pierre avec le Désavantage “Interdits de Brorne”.\nCette compétence est une attaque vocale, une nouvelle technique de combat à distance basée sur la magie et une Clé vocale. Le magicien doit faire face à sa cible et produire un son qui agresse la matière. II doit faire un jet de Cri de la pierre + Sphère de Pierre Difficulté 15 +/- malus suivant les conditions de combat) pour toucher une cible et lui infliger Mental + 10 + 1D10 dégâts. La portée est de 5m en hurlant en bataille, à 10m en escarmouche, à 20m en duel et à 40 à 60m par temps calme. Il n'y a ni armure, ni esquive ou parade. Le son est audible de loin. En cas d’échec critique, c’est le magicien qui subit les dommages."),
  creatureNaturalWeapon(title: "Arme naturelle pour les créatures", family: SkillFamily.combat, canInstantiate: false),

  // Mouvement
  acrobatie(title: "Acrobatie", family: SkillFamily.mouvement, description: "Permet d'effectuer toutes sortes de mouvements complexes, tels que chutes, bonds et autres manœuvres liées à l'équilibre du personnage, telles que marcher sur une corde, etc.\nExemples de Spécialisations : funambulisme, contorsions, sauts périlleux, saut à la perche, etc."),
  athletisme(title: "Athlétisme", family: SkillFamily.mouvement, description: "Permet d'effectuer des actions physiques fondées sur l'endurance, la souplesse, l'agilité et la précision.\nExemples de Spécialisation : course de fond, course de vitesse, saut en hauteur, saut en longueur, etc."),
  cavalerieAerienne(title: "Cavalerie aérienne", family: SkillFamily.mouvement, forbidden: true, description: "Permet de diriger des animaux volants dressés pour supporter un cavalier et lui obéir. Elle permet également de juger de l'état physique, de la fiabilité et du prix de la créature.\nExemples de Spécialisation : par monture."),
  combatMonte(title: "Combat monté", family: SkillFamily.mouvement, reservedCastes: [Caste.combattant], description: "Permet de développer une technique de combat efficace à cheval ou à dos d'un type de créature particulier. Chaque fois que le personnage se bat dans ces conditions, il effectue tout d'abord un jet de Physique + Combat monté contre une Difficulté de 15. Ce jet remplace le simple jet d’équitation lors du Combat monté (Livre de base p.188) pour les actions offensives et défensives, mais pas les Charges.\nPour chaque Niveau de Réussite obtenu, il peut lancer un dé d'Initiative supplémentaire ou diminuer de 5 la Difficulté d'une attaque effectuée dans le toure Une réussite simple lui confère simplement un bones de +2 sur son premier dé d'action. Il est possible de dépenser des pointes de Maîtrise sur ce jet mais, dans ca cas, le personnage ne peut en regagner aucun durant le tour − car il s'applique avant tout à maîtriser sa monture.\nLe niveau de cette Compétence ne peut en aucun cas être supérieur à celui de la Compétence Équitation du personnage."),
  endurance(title: "Endurance", family: SkillFamily.mouvement, reservedCastes: [Caste.combattant], description: "Permet au personnage de résister mieux et plus longtemps à un effort, une douleur ou un malaise, quelle qu'en soit la nature. Pour cela, il faut réussir un jet de Physique + Endurance contre une Difficulté fixée par la situation.\nPour les malus liés aux blessures pendant 1 tour + 1 par Niveau de Réussite, la Difficulté est de 10 + 3 fois le malus de blessure le plus important. Pour prolonger un effort, un jet contre une Difficulté de 10 permet, pour chaque Niveau de Réussite, de poursuivre une action épuisante pendant 1 tour, 1 minute ou 1 heure, en fonction de l'effort (soutenir une herse se compte en tours ; nager en armure ou à contre-courant, en minutes ; et courir, en heures.\nÀ titre d'information, un personnage ne disposant pas de cette Compétence effectue le jet avec Physique + Résistance contre une Difficulté identique, et ne peut obtenir aucun Niveau de Réussite. Dans le dernier cas, il ne peut donc prolonger l'effort que d'une seule unité de temps.\nLe niveau de cette Compétence ne peut en aucun cas être supérieur à celui de la Résistance ou de la Volonté du personnage (la plus élevée des deux)."),
  equitation(title: "Équitation", family: SkillFamily.mouvement, description: "Permet de monter des chevaux, des lézards géants et des créatures domestiquées, mais aussi d'estimer l'état de fraîcheur et la santé d'une bête, d'estimer son prix de vente. Les dragons ne sont JAMAIS considérés comme des montures et ne nécessitent aucune compétence pour s'y maintenir. En effet, on ne chevauche pas un dragon, c'est lui qui vous emmène.\nExemples de Spécialisation : cheval, poney, lézard géant, âne, etc."),
  escalade(title: "Escalade", family: SkillFamily.mouvement, description: "Permet de connaître et de pratiquer les différentes techniques d'escalade sur différents types de parois.\nExemples de Spécialisation : par milieu (muraille de glace, parois rocheuses, murs maçonnés, etc.)"),
  esquive(title: "Esquive", family: SkillFamily.mouvement, description: "Permet d'effectuer des mouvements pour éviter des coups ou protéger des zones vitales, amorttir des chutes ou de s'écarter de la trajectoire de certaines armes lancées (comme un boulement ou une arme de jet que l'on voit venir). L'Esquive ne permet pas d'éviter les projectiles.\nExemples de Spécialisation : esquive acrobatique (demande de l'espace libre et de ne pas porter d'armure plus lourde que du cuir souple), esquive du lutteur (contre la Compétence Corps à corps), esquive contre un coup spécial, etc. Il n'est pas possible de se spécialiser contre des familles d'armes."),
  natation(title: "Natation", family: SkillFamily.mouvement, description: "Permet de nager et de plonger dans différents cours d'eau. Il est impossible de nager en armure plus lourde que le cuir souple. Des Niveaux de Réussite peuvent servir à secourir une personne en train de se noyer.\nExemples de Spécialisation : plongée en apnée (ramassage de coquillages), natation en torrents, etc."),

  // Theorie
  anticipationDesOrages(title: "Anticipation des orages", family: SkillFamily.theorie, reservedCastes: [Caste.mage], description: "Cette Compétence est réservée aux Mages du Feu.\nCette Compétence permet au mage de prévoir l'orientation, la force et la durée d'un orage qu'il voit. Cela peut avoir quelque utilité quand la Clé d'un sortilège particulier est la foudre. De plus, cela permet aussi de prévenir de l'arrivée d'une tempête, en mer comme sur terre. Cette compétence particulière est connue des mages de Szyl pour les tornades, et de ceux d'Ozyr pour les tempêtes.\nExemples de Spécialisation : par type de milieu."),
  castes(title: "Castes", family: SkillFamily.theorie, description: "Permet de connaître les mœurs, les insignes, les principaux représentants et les Interdits des différentes castes.\nExemples de Spécialisation : par caste."),
  chimie(title: "Chimie", family: SkillFamily.theorie, forbidden: true, description: "Permet de décrypter les mécanismes qui régissent l'alchimie pour la systématiser. Cette rationalisation ôte à l'alchimie son côté hasardeux et obscurantiste et permet de mieux calculer son travail. En élaborant ses équations de réaction, le chimist peut soustraire son niveau de Compétence à la difficulté d'une préparation. Cette nouvelle difficulté, dite Difficulté chimique, peut être transcrite en une formule fiable, transmissible à d'autres chimistes. Une potion chimique (et plus alchimique ainsi transcrite possède une Difficulté fixe égale à la Difficulté chimique. On ne peut améliorer une formule (et faire baisser la Difficulté chimique) que si l'on possède une COmpétence supérieure à celle du chimiste qui l'a établie. La nouvelle Difficulté chimique qu'il est possible de transcrire est alors de (Difficulté alchimique mois Compétence Chimie).\nTranscrire une potion alchimique en potion chimique nécessite 3h par point de Difficulté alchimique. Lire une formule chimique requirt la Compétence Chimie et un jet de Difficulté égale à celle de la potion chimique.\nLe niveau de cette Compétence ne peut dépasser la Tendance Homme du personnage + 5.\nExemples de Spécialisation : par type de potion alchimique."),
  conception(title: "Conception", family: SkillFamily.theorie, reservedCastes: [Caste.artisan], description: "Permet au personnage de dresser des ébauches, de dessiner des plans et de décomposer les étapes de réalisation d'un projet.\nCette Compétence s'utilise pour ses propres entreprises ou celles d'un autre personnage avant toute Compétence susceptible d'être planifiée : Géographie, Cartographie, Artisanat (tous), Mécanismes ou Pièges. Les Niveaux de Réussite sur un jet de Mental + Conception Difficulté 10 octroient des bonus indirects (+1/NR) pour ces compétences. Il est possible d'utiliser cette Compétence même si le personnage ne maître pas la Compétence adaptée à son projet, mais la Difficulté du jet reste augmentée de 5.\nIl est possible de spécialiser dans un domaine précis de Conception, du moment que le personnage possède la Compétence en rapport − par exemple, Conception de plans nécessite Cartographie ou Orientation.\nExemples de Spécialisation : par Compétence."),
  connaissanceDeLaMagie(title: "Connaissance de la magie", family: SkillFamily.theorie, reservedCastes: [Caste.erudit, Caste.mage, Caste.prodige], description: "Permet de connaître les différentes Sphères et Disciplines de magie, ainsi que les effets des sorts, les Clés, les écoles, etc.\nCette Compétence est réservée aux mages, aux érudits et aux Prodiges.\nExemples de Spécialisation : par Sphère de magie ou par Discipline de magie."),
  connaissanceDesAnimaux(title: "Connaissance des animaux", family: SkillFamily.theorie, description: "Permet de connaître le mode de vie, l'écosystème, le cycle de reproduction et les habitudes alimentaires des animaux et des créatures.\nExemples de Spécialisation : par type d'animaux (poissons, rongeurs, félins, etc.)"),
  connaissanceDesDragons(title: "Connaissance des dragons", family: SkillFamily.theorie, reservedCastes: [Caste.erudit, Caste.prodige], description: "Permet de connaître certains mystères sur le mode de vie, la magie, l'histoire, la politique et la philosophie des dragons.\nCette Compétence est réservée aux érudits et aux Prodiges.\nExemples de Spécialisation : par lignage de dragon (enfants de Kroryn, de Nenya, etc.)"),
  connaissanceDeLaPierre(title: "Connaissance de la pierre", family: SkillFamily.theorie, reservedCastes: [Caste.mage], description: "Cette Compétence est réservée aux Mages de la Pierre.\nLe magicien peut expliquer l’évolution tectonique qu’un paysage y compris ses points de rupture et ses failles. Cela peut paraître peu exploitable en situation d’aventure sauf que ce savoir lui permet aussi de repérer les meilleurs endroits pour provoquer un glissement de terrain, pour faire basculer un rocher dans une pente ou pour monter un piège à base de pierre. Pour ce qui est de repérer les éléments exploitables, on fera le jet avec le Mental. Pour concrétiser, il faudra un jet sous Manuel.\nS’utilise systématiquement (et si le milieu s'y prête) avant tout jet de Survie (Montagnes), Géographie, Cartographie ou Pièges. Les NR (Jet Diff. 10) octroient des bonus indirects DOUBLES pour ces Compétences. Exemples de Spécialisation : par région."),
  facture(title: "Facture", family: SkillFamily.theorie, reservedCastes: [Caste.mage], description: "Cette compétence est uniquement accessible aux Mages du Métal qui ont le désavantage “Malédiction de Kezyr”.\nEn touchant un objet, qu'il soit magique ou non, et en réussissant un jet de Mental + Facture avec une Difficulté égale à la Difficulté de création de l'objet, le mage peut en déterminer non seulement l'âge approximatif, mais aussi le type de fabrication, l'origine − avec un Niveau de Réussite − et même le nom du fabricant − avec deux Niveaux de Réussite.\nLa déterioration de l'objet peut infliger des malus lors de l'utilisation de cette Compétence."),
  fauneEtFlore(title: "Faune et flore", family: SkillFamily.theorie, reservedCastes: [Caste.prodige], description: "Cette compétence est réservée aux Prodiges.\nPermet au personnage de posséder une connaissance précise de la plupart des espèces vivantes, qu'elles soient animales, végétales ou minérales. Cette Compétence, qui intègre des notions d'herboristerie et de biologie, permet entre autre de distinguer les espèces ou d'en utiliser certaines particularités.\nCe savoir empirique et ancestral s’utilise systématiquement avant tout jet d’Herboristerie, Connaissance des animaux, Premiers soins, Alchimie ou Matières premières. Les NR (Jet Diff. 10) octroient des bonus indirects pour toutes ces Compétences.\nExemple de Spécialisation : par milieu"),
  geographie(title: "Géographie", family: SkillFamily.theorie, reservedCastes: [Caste.commercant, Caste.erudit, Caste.voyageur], description: "Permet de connaître le relief, le climat, les voies de communication et les différentes régions du monde ainsi que la géopolitique, les us et coutumes, etc.\nCette Compétence est réservée aux commerçants, aux érudits et aux voyageurs.\nExemples de Spécialisation : par région."),
  histoire(title: "Histoire", family: SkillFamily.theorie, reservedCastes: [Caste.erudit], description: "Permet de connaître les dates et les noms des personnages impliqés dans les différents événements de l'histoire. Elle rassemble aussi bien les faits précis que les légendes, les anecdotes et les détails méconnus du peuple.\nCette Compétence est réservée aux érudits.\nExemples de Spécialisation : par époque particulière ou par région (Âge des Fondations, Empire de Solyr, Marches Alyzées, etc.)"),
  interpretationDesReves(title: "Interprétation des rêves", family: SkillFamily.theorie, reservedCastes: [Caste.mage], description: "Cette compétence est réservée aux Mages des Rếves.\nLe mage peut expliquer les rêves qu’il fait ou qu’on lui raconte. S’il y a message, il saura l’interpréter. Dans la majorité des cas, le rêve est une réminiscence mais parfois il peut aussi être le reflet du futur où du présent. Ainsi, si la personne analysée est confrontée à un problème, ses rêves peuvent lui apporter inconsciemment la solution.\nRemplace Psychologie en ce qui concerne le décryptage des rêves en vue de soigner un Déséquilibre mental ou une Phobie. Cette compétence peut apporter un bonus indirect en Psychologie si les rêves sont utilisés comme base du travail thérapeuthique. Par un jet d'une Difficulté fixée par le MJ, elle peut également servir à comprendre les rêves prophétiques des Étoiles ou les messages oniriques induits.\nExemples de Spécialisation: par sexe et tranche d'âge."),
  lois(title: "Lois", family: SkillFamily.theorie, reservedCastes: [Caste.commercant, Caste.erudit, Caste.protecteur], description: "Permet de connaître les lois et les règlements en vigueur dans différents milieux, tels que cités, régions et corps de métier particuliers.\nCette Compétence est réservée aux commerçants, aux érudits et aux protecteurs.\nExemples de Spécialisation : loi criminelle, règlements commerciaux, droit nobiliaire, etc."),
  mathematiques(title: "Mathématiques", family: SkillFamily.theorie, forbidden: true, description: "Bien au-delà des opérations de base, cette Compétence permet l'usage de l'algèbre, des équations du second degré, des interprétations graphiques et des statistiques.\nLe niveau de cette Compétence ne peut dépasser la Tendance Homme du personnage + 5."),
  necromancie(title: "Nécromancie", family: SkillFamily.theorie, reservedCastes: [Caste.mageNoir], description: "Cette compétence est réservée aux Mages de l'Ombre.\nCette Compétence rassemble toutes les comnaissances liées aux morts-vivants, à leur métamorphose et à leurs coutumes. Elle peut s’utiliser de différentes façons. Avec l’Attribut Mental, elle permet de connaître les aspects morbides du Fatalisme, les différentes catégories de morts-vivants et leurs pouvoirs attribués. Avec Manuel, elle permet de procéder aux rites funéraires et aux actes de conservation des corps, comme la momification et les embaumements. Enfin, avec Social, elle permet d’évoluer dans la société mort-vivante de Nadjar et d'éviter les impairs qui froisseraient les Patriarches. Bien sûr, bien peu osent explorer trop avant cet aspect de la Compétence."),
  orientation(title: "Orientation", family: SkillFamily.theorie, reservedCastes: [Caste.prodige, Caste.voyageur], description: "Permet de se repérer et milieu naturel, en utilisant les runes de voyage, les étoiles, la mousse des arbres et… son intuition.\nCette Compétence est réservée aux Prodiges et aux voyageurs.\nExemples de Spécialisation : par milieu (forêts, jungles, montagnes, plaines, littoral, etc.)"),
  philosophie(title: "Philosophie", family: SkillFamily.theorie, requireConcreteImplementation: true, description: "En choisissant cette Compétence, le joueur doit impérativement opter pour l'une des trois philosophies : humaniste, draconiste ou fataliste.\nPermet de connaître et d'exposer clairement les thèses concernées à un profane ou à un sympathisant. Par un exposé méthodique, l'orateur peut puiser dans son savoir pour convaincre son auditoire, mais aussi trouver une certaine vérité dans ses actes et ainsi renforcer sa propre croyance. Cette Compétence regroupe également la connaissance des écrits et des discours des plus grands penseurs de sa croyance.\nExemples de Spécialisation : aucune."),
  physique(title: "Physique", family: SkillFamily.theorie, forbidden: true, description: "Permet de mettre en équation les divers phénomènes naturels observés par les scientifiques et de décrypter leurs mécanismes. Ainsi, la dynamique des fluides, l'optique ou l'étude des gaz font partie de cette Compétence.\n\nLe niveau de cette Compétence ne peut dépasser la Tendance Homme du personnage + 5, ni dépasser le niveau de la Compétence Mathématiques."),
  perceptionClimatique(title: "Perception climatique", family: SkillFamily.theorie, reservedCastes: [Caste.mage], description: "Cette compétence est réservée aux Mages des Vents, de la Nature et des Océans.\nCette Compétence permet au mage de prévoir la nature, l’orientation, la force et la durée de toute altération climatique.\nExemples de Spécialisation : par phénomène climatique."),
  strategie(title: "Stratégie", family: SkillFamily.theorie, reservedCastes: [Caste.combattant, Caste.protecteur], description: "Permet de déterminer un plan d'attaque, d'organiser une défense et de dresser des tactiques de combat.\nCette Compétence est réservée aux combattants et aux protecteurs.\nExemples de Spécialisation : petites unités, grandes armées, troupes forestières, patrouilles frontalières, etc."),

  // Pratique
  alchimie(title: "Alchimie", family: SkillFamily.pratique, reservedCastes: [Caste.artisan, Caste.erudit], description: "Permet de connaître et d'utiliser les ingrédients et le matériel nécessaires à la confection de philtres, d'onguents, de poisons, de poudres et de substances chimiques. Certaines applications sont formellement interdites par les Grands Dragons − comme les mélanges explosifs, par exemple. Le niveau de cette Compétence ne peut dépasser la Tendance Homme du personnage + 5.\nCette Compétence est réservée aux artisans et aux érudits.\nExemples de Spécialisation : poisons, antidotes, potions d'artisanat, etc."),
  analyse(title: "Analyse", family: SkillFamily.pratique, reservedCastes: [Caste.mage], description: "Permet de déterminer avec précision les énergies contenues ou mises en œuvre dans un sortilège, un effet magique, un objet ou un lieu enchanté. En établissant un contact physique, le personnage peut effectuer un jet de Mental + Analyse contre une Difficulté de 10 pour découvrir qu'un objet est enchanté. En augmentant cette Difficulté de 5, il peut demander à apprendnre une information supplémentaire, telle que la Sphère ou la Discipline impliquées, la puissance de la magie présent, ses effets, etc. Chaque information augmente de 5 la Difficulté de base du jet.\nCette Compétence peut être utilisée pour reconnaître un effet au moment où celui-ci est déclenché, mais la Difficulté de base est augmentée de 5. Elle peut également être employée sur un être vivant, mais ce dernier aura droit à un jet de Mental + Volonté contre une difficulté de 15 pour comprendre qu'il fait l'objet d'une recherche. Enfin, elle peut aider à percevoir une matrice de sort. Elle octroie un bonus indirect de +1/NR (Jet Diff. 10) au jet de Mental + Empathie nécessaire pour percevoir la matrice.\nExemples de Spécialisation : par type de support (arme, armure, vêtements, bijoux…)"),
  astrologie(title: "Astrologie", family: SkillFamily.pratique, reservedCastes: [Caste.erudit], description: "Permet de connaître et d'utiliser les étoiles afin de s'orienter, de calculer des positions et de dresser des cartes du ciel, mais aussi prédire certains événements de l'avenir et d'établir des thèmes d'augure susceptibles de révéler certains traits de caractère. Le niveau de cette Compétence ne peut pas dépasser la Tendance Homme du personnage + 5.\nCette compétence est réservée aux érudits.\nExemples de Spécialisation : thèmes d'augure, mouvement des astres, répertorier, nommer, etc."),
  cartographie(title: "Cartographie", family: SkillFamily.pratique, reservedCastes: [Caste.erudit, Caste.voyageur], description: "Permet de comprendre et de confectionner toutes sortes de plans, de cartes et de relevés topographiques relativement précis. Il n'est pas indispensable de posséder la Compétence Lire et écrire pour développer cette Compétence, il suffira simplement d'utiliser des pictogrammes et des symboles.\nCette Compétence est réservée aux érudits et aux voyageurs.\nExemples de Spécialisation : carte commerciale, militaire, politique, etc."),
  cartographierLesReves(title: "Cartographier les rêves", family: SkillFamily.pratique, reservedCastes: [Caste.mage], description: "Cette compétence est est uniquement accessible aux Mages des Rếves avec le désavantage “Marque de Nenya” ou aux Augures Noirs ayant déjà la Sphère des Rêves à 3.\nCette Compétence très spécialisée permet à un mage ayant accès aux rêves d’une personne de savoir s’y diriger sans s’y perdre et de pouvoir anticiper un réveil. Seuls les mages possédant le sort Psychonaute ont l’utilité de ce savoir. Les autres peuvent s’en servir pour comprendre la structure mentale d’une personne, sa psychologie, sans plus.\nPour les Augures Noirs, le niveau de cette Compétence ne peut dépasser 5 + Tendance Dragon.\nExemples de Spécialisation : par sexe et tranche d’âge."),
  chirurgie(title: "Chirurgie", family: SkillFamily.pratique, forbidden: true, description: "Permet de prcéder à des soins élabores. Cette forme de Médecine “scientifique” est proscrite par les Lois draconiques. En effet, il est blasphématoire de souiller le corps conçu par les Dragons. Chirurgie s'utilise généralement avec l'Attribut Manuel (pour opérer) ou Mental (pour diagnostiquer).\nExemples de Spécialisation : sutures, fractures ouvertes, etc."),
  estimation(title: "Estimation", family: SkillFamily.pratique, description: "Permet d'analyser la qualité d'un objet manufacturé et de fixer un prix de vente et/ou d'achat convenable.\nExemples de Spécialisation : par type de marchandise (armes, épices, vins, etc.)"),
  explosifs(title: "Explosifs", family: SkillFamily.pratique, forbidden: true, description: "Permet d'utiliser et de fabriquer des explosifs à base de poudre ou de sustances alchimiques. Cette Compétence est strictement interdite par les Lois draconiques. Le niveau de cette Compétence ne peut pas dépasser la Tendance Homme du personnage + 5. Explosifs s'utilise généralement avec l'Attribut Mental.\nCette Compétence permet de préparer de la poudre noire, une des principales inventions Humanistes. Elle ne permet pas par contre de s'en servir.\nLorsqu'un personnage utilise la poudre noire (que ce soit avec Explosifs, Armes à poudre noire ou encore dans le cas des Armes de siège), il peut choisir d'utiliser ou non les Tendance. S'il les utilise, la poudre explose de façon incontrôlée si les trois dés indiquent le même résultat (triple 1, triple 2, etc.). S'il ne les utilise pas, la poudre peut exploser lors d'un échec critique. Le personnage voit alors toute la poudre noire dans un rayon d'un mètre exploser subitement. Selon la quantité mise en œuvre, le meneur jugera des blessures, des mutilations ou du décès de l'infortuné artificier.\nExemples de Spécialisation : explosifs en poudre, explosifs liquides, explosifs de spectacle, poudre noire, etc."),
  explosifsDeBrorne(title: "Explosifs de Brorne", family: SkillFamily.pratique, reservedCastes: [Caste.mage], description: "Cette Compétence est réservée aux Mages de la Pierre.\nCette Compétence est identique à Explosif, à la différence qu’elle est autorisée pour les magiciens de Brorne. L'exploitation des minéraux a fait que, naturellement, les sorciers des Creusets ont découvert des propriétés explosives à certaines matières mélangées entre elles. Plutôt que de voir ses serviteurs enfreindre ses lois, il a préféré donner son accord pour une utilisation restreinte, et uniquement par des magiciens, des explosifs. Un magicien qui maîtrise cette Compétence devra toujours affirmer qu’il s’agit de magie et non de chimie. Les dommages possibles vont jusqu’à (Compétence/2)D10, pour des Difficultés allant de 15 à 25 selon les effets recherchés et la zone touchée (Compétence en m²). Les explosifs de Brorne sont soumis aux même règles d'explosion que la poudre noire.\nExemples de Spécialisation: par type de mixture (aveuglants, explosifs…)"),
  forcesInvisible(title: "Forces invisibles", family: SkillFamily.pratique, forbidden: true, description: "Sûrement la plus honnie des Compétences, Forces invisibles prétend expliquer les phénomènes magiques par le biais de la science. Très expérimentale et hasardeuse, cette Compétence regroupe l'étude des éclairs, de la vapeur, de la vulcanologie ou de la climatologie, bien qu'aucun des noms n'ait encore réellement de sens en Kor ou en Nésora.\nLe niveau de cette Compétence ne peut dépasser la Tendance Homme du personnage + 5."),
  herboristerie(title: "Herboristerie", family: SkillFamily.pratique, reservedCastes: [Caste.erudit, Caste.prodige, Caste.voyageur], description: "Permet de connaître, de repérer, de conserver et d'ulitiser efficacement les herbes, plantes, fleurs et autres végétaux. Elle permet de savoir réaliser des macérations, des pâtes pour pansements et des tisanes médicinales. Elle est très utile pour assembler les ingrédients d'une potions alchimique mais ne permet pas de la distiller.\nCette Compétence est réservée aux érudits, aux Prodiges et aux voyageurs.\nExemples de Spécialisation : par type d'herbe (épices, herbes curatives, plantes des marécages, etc.)"),
  investigation(title: "Investigation", family: SkillFamily.pratique, reservedCastes: [Caste.protecteur], description: "Permet au personnage de mener une enquête méticuleuse et d’effectuer des recoupements précis entre différents éléments. En théorie, cette Compétence est surtout utile lorsqu'elle est utilisée dans une pièce ou une zone délimitée, mais elle peut également permettre d’associer des événements distants ou de comparer les récits de différentes personnalités. Un jet réussi permet d’obtenir un indice, un autre par Niveau de Réussite, et la Difficulté peut être fixée par la taille de l’endroit, le nombre d’indices ou le temps écoulé entre les révélations/actions des suspects.\nExemples de Spécialisation : par type d'enquête (crime, vol, complot)."),
  jardinage(title: "Jardinage", family: SkillFamily.pratique, reservedCastes: [Caste.mage], description: "Cette Compétence est réservée aux Mages de la Nature.\nLe mage peut non seulement organiser et faire fructifier un jardin ou un verger, mais il a aussi les connaissances nécessaires pour bien se comporter vis-à-vis de la nature − quels fruits prendre, pourquoi il ne faut pas mettre le doigt dans une plante carnivore, etc − et peut déceler intuitivement les liens magiques entre le milieu et le règne végétal présent. Le mage peut aussi conseiller les paysans, les bûcherons et tout ce qui a un rapport avec la nature."),
  langageDesAnimaux(title: "Langage des animaux", family: SkillFamily.pratique, reservedCastes: [Caste.mage], description: "Cette Compétence est réservée aux Mages de la Nature.\nPermet au magicien de pouvoir comprendre le comportement d'un animal et le message qu'il désire éventuellement faire passer. L'animal ne pourra pas communiquer des idées et des concepts trop complexes, mais des états ou des sensations − peur, douleur, faim, tristesse, etc. Réussir ce jet contre une Difficulté de 10 donne un bonus de +1 par Niveau de Réussite à un jet de Dressage."),
  langageDesPlantes(title: "Langage des plantes", family: SkillFamily.pratique, reservedCastes: [Caste.mage], description: "Cette Compétence est réservée aux Mages de la Nature.\nLe mage peut analyser et comprendre la logique de l'écosystème floral de l'endroit où il se trouve. Il peut déceler des anomalies, repérer les bonnes plantes et les endroits susceptibles de les cacher. Combiné avec la compétence Herboristerie, cela permet d'ouvrir une boutique d'apothicaire.\nCette Compétence s’utilise systématiquement avant tout jet de Jardinage, Herboristerie ou Matières premières (d’origine végétale). Les NR (Jet Diff. 10) octroient des bonus indirects DOUBLES pour ces Compétences.\nExemples de Spécialisation : par milieu."),
  langueDesSignes(title: "Langue des signes", family: SkillFamily.pratique),
  lireEtEcrire(title: "Lire et écrire", family: SkillFamily.pratique, reservedCastes: [Caste.commercant, Caste.erudit], description: "Permet de lire et d'écrire le langage draconique, de composer des poèmes et des discours, de rédiger des textes élaborés, etc.\nCette Compétence est réservée aux commerçants et aux érudits.\nExemples de Spécialisation : discours, pièces de théâtre, ballades, etc."),
  matieresPremieres(title: "Matières premières", family: SkillFamily.pratique, reservedCastes: [Caste.artisan], description: "Permet de juger du potentiel et de la qualité d'une matière première (bois, minéraux, plantes, métaux, etc.) en vue de sa transformation.\nCette Compétence est réservée aux artisans.\nExemples de Spécialisation : par marchandise (herbes, bois, minerais destinés à la forge, etc.)"),
  medecine(title: "Médecine", family: SkillFamily.pratique, reservedCastes: [Caste.erudit, Caste.prodige], description: "Permet de diagnostiquer une maladie, de définir et d'appliquer le meilleur traitement à une blessure ou un mal quelconque. La Compétence Médecine est plus théorique que Premiers soins et se fonde sur un diagnostic et des expérinces passées ainsi que sur l'usage des traitements apothicaires.\nCette Compétence est réservée aux érudits et aux Prodiges.\nExemples de Spécialisation : maladies, coupures, fractures, médecine de guerre, etc."),
  meditation(title: "Méditation", family: SkillFamily.pratique, reservedCastes: [Caste.mage, Caste.prodige], description: "Cette compétence est réservée aux Mages et aux Prodiges.\nPour les prodiges, permet d'effacer un cercle de Tendance acquis récemment. La Difficulté du jet dépend du temps écoulé depuis l'apparition de ce cercle (15 pour une heure, 20 pour une demi journée, 25 pour une semaine et 30 pour un Augure).Pour les mages, permet de regagner des Points de Magie dans les Réserves de son choix, en réussissant un jet de Méditation + Empathie + Niveau de Statut contre une Difficulté de 15. Si le jet est réussi, le personnage regagne 1 Point de Réserve de Volonté + 1 par Niveau de Réussite, qu’il peut attribuer à n’importe quelle Réserve Élémentaire — du moment que cet élément est présent dans son environnement. Cette Difficulté est valable pour une méditation de 3 heures et est augmentée de 5 pour chaque heure sacrifiée. Il est impossible de méditer moins d’une heure ou de méditer plus d’une fois par jour.\nExemples de Spécialisation: selon l'environnement (dans le silence, dans les bois…)\n"),
  oniromancie(title: "Oniromancie", family: SkillFamily.pratique),
  premiersSoins(title: "Premiers soins", family: SkillFamily.pratique, description: "Permet de stopper des saignements et d'appliquer des soins d'urgence. Les effets de cette Compétence sont nettement inférieurs à ceux de la Compétence Médecine. La Compétence Premiers soins nécessite des torchons, la cautérisation et la désinfection à l'eau de vie…\nExemples de Spécialisation : soins des coups, soins des coupures, etc."),
  psychometrie(title: "Psychométrie", family: SkillFamily.pratique, reservedCastes: [Caste.mage], description: "Permet, à l’image du Privilège des artisans, de ressentir le passé d’un lieu ou d’un objet grâce aux énergies magiques. En réussissant un jet de Mental + Empathie contre une Difficulté de 15, le personnage peut apprendre une information, plus une par Niveau de Réussite — événements majeurs qui s’y sont déroulés, combat, rituel, aura magique du porteur d’une arme, etc. Ces informations se traduisant par des couleurs, des émotions, le personnage reste dépendant de la “puissance” de ce qu’il observe pour ce qui est de la qualité des renseignements. Ainsi, une vulgaire lame d’acier ne pourra guère informer le mage, tandis qu’une clairière où se déroulent de nombreuses cérémonies lui offrira des informations très précises — et même de véritables visions."),
  soinsOniriques(title: "Soins oniriques", family: SkillFamily.pratique, reservedCastes: [Caste.mage], description: "Cette compétence est réservée aux Mages des Rếves.\nQuand un mage de Nenya utilise cette Compétence, on a l'impression qu’il chante une simple berceuse. En fait, ce chant plonge un blessé ou un malade dans un profond sommeil, ce qui multiplie par deux la vitesse de récupération - fatigue, Points de Magie, Blessures. Cette compétence fonctionne aussi pour les mages affligés de troubles du sommeil, comme certains Magiciens du Feu. Si le mage a un instrument de musique et qu'il réussit à l’utiliser - Diff. 15 — en même temps, il gagne un bonus de 5. Chaque quart de journée compte double pour calculer la régénération durant cette transe.\nExemples de Spécialisation : par sexe et tranche d’âge."),
  survie(title: "Survie", family: SkillFamily.pratique, requireConcreteImplementation: true, reservedCastes: [Caste.voyageur], description: "Permet de connaître les moyens de subsister en milieu naturel et d'éviter les dangers de ces endroits (éboulements, sables mouvants, déshydratation, etc.) Cette Compétence permet de préserver son énergie, son équipement, de trouver de quoi s'alimenter sommairement et de quoi boire.\nIl est nécessaire de choisir un des milieux suivants et de développer une Spécialisation pour chaque milieu : forêts, montagnes, plaines, marécages, zones glaciaires, collines, déserts, etc.\nCette Compétence est réservée aux voyageurs.\nExemples de Spécialisation : par région précise (marais de Path, Collines de Fer, Chaîne de la Griffe, etc.)"),
  toucheDePerfection(title: "Touche de perfection", family: SkillFamily.pratique, reservedCastes: [Caste.mage], description: "Cette compétence est réservée aux Mages du Métal ou des Rêves.\nCette Compétence doit être associée à une autre ayant un caractère artistique ou artisanal. En réussissant un jet contre une Difficulté égale à la Difficulté de la création, le mage peut ensuite ajouter 1 Niveau de Réussite + 1 par Niveau de Réussite supplémentaire. Attention, cela ne concerne pas les actions magiques.\nExemples de Spécialisation : par type de support."),
  vieEnCite(title: "Vie en cité", family: SkillFamily.pratique, reservedCastes: [Caste.commercant, Caste.protecteur], description: "Permet de connaître l'organisation, les lieux importants et les personnalités influentes d'une cité, obtenir des informations, d'intercepter ou de répandre des rumeurs. Cette Compétence s'utilise avec Mental pour déterminer une localisation, un itinéraire, un contact, mais avec Social pour obtenir l'entrées d'une taverne gardée, contacter les miliciens, négocier avec les gosses des rues, etc.\nCette Compétence est réservée aux commerçants et aux protecteurs.\nExemples de Spécialisation : par type de population (prostituées, miliciens, portefaix, gosses, boutiquiers, etc.)"),
  vieEnForet(title: "Vie en forêt", family: SkillFamily.pratique, reservedCastes: [Caste.prodige], description: "Cette Compétence est réservée aux Prodiges.\nCe savoir intuitif s’utilise uniquement en milieu forestier et systématiquement avant tout jet d’Orientation, Survie (forêts), Pister, Discrétion, Connaissance des animaux ou Pièges. Les NR (Jet Diff. 10) octroient des bonus indirects pour toutes ces Compétences.\nExemple de Spécialisation : par région."),

  // Technique
  armesDeSiege(title: "Armes de siège", family: SkillFamily.technique, reservedCastes: [Caste.combattant, Caste.protecteur], description: "Permet de connaître et de manier les armes utilisées pour défendre des fortifications, comme les béliers, les trébuchets ou les catapultes de siège. Le niveau de cette Compétence ne peut dépasser la Tendance Homme du personnage + 5.\nCette Compétence est réservée aux combattants et aux protecteurs.\nExemples de Spécialisation : par engin de siège."),
  armesMecaniques(title: "Armes mécaniques", family: SkillFamily.technique, forbidden: true, description: "Permet de connaître et de manier les armes à fonctionnement mécanique, telles que les arbalètes, les harpons mécaniques et les balistes légères. La détention, la fabrication et l'utilisation de ces armes sont formellement interdites par les Dragons. Le niveau de cette Compétence ne peut dépasser la Tendance Homme du personnage + 5. Cette Compétence s'utilise généralement avec l'Attribut Manuel.\nExemples de Spécialisation : par arme."),
  armure(title: "Armure", family: SkillFamily.technique, reservedCastes: [Caste.protecteur], description: "Permet au personnage de maîtriser le port, l'assemblage el les mécanismes de réparation d’armures et d’éléments de protection, tels que les heaumes, les renforts et les harnais de monture. Permet (avec Physique), de réduire la pénalité d’encombrement de 1+1/NR (Diff.10). Pour réparer (Manuel), elle permet UN seul jet et répare 1+1/NR points de protection (après quoi un artisan est nécessaire). Elle peut remplacer Estimation pour évaluer le prix d’une armure ou d’un bouclier.\nExemples de Spécialisation : par catégorie d'armure."),
  artisanat(title: "Artisanat", family: SkillFamily.technique, requireConcreteImplementation: true, reservedCastes: [Caste.artisan, Caste.combattant], description: "Permet de maîtriser les techniques de confection de différents objets manufacturés, comme la forge, la sculpture, lorfèvrerie, etc. Il est impératife de développer une Spécialisation pour chaque type d'artisanat.\nCette Compétence est considérée comme réservée aux artisans et aux combattants.\nExemples de Spécialisation : archerie (confection de flèches), forge (d'armes), forge (d'outils), etc."),
  artisanatElementaire(title: "Artisanat élémentaire", family: SkillFamily.technique, reservedCastes: [Caste.artisan], requireConcreteImplementation: true, description: "Permet au personnage de manipuler les éléments à la façon d'une simple matière, en vue de forger et de sculpter une œuvre artistique. Ce travail nécessite les outils nécessaires au travail de la matière. Lorsqu'il choisit cette Compétence, le personnage doit impérativement choisir une Sphère élémentaire dont il possède la Compétence. Son niveau en Artisanat élémentaire ne peut en aucun cas dépasser celui de sa Sphère + 2. La Difficulté des jets d'Artisanat élémentaire est fixée par les mêmes critères que n'importe quel jet d'Artisanat − voir confection des objets − mais le personnage doit dépenser 1 Point de magie de la Sphère correspondante pour chaque niveau de qualité obtenu ou souhaité.Une création élémentaire perdure une semaine et coûte 1 point de magie (plus ceux des NR), puis est doublée par chaque point supplémentaire (deux semaines pour 2 pts, 4 semaines pour 3 pts, 8 semaines pour 4, etc…). Tous les jets d’enchantement ont un bonus égal au nombre de points de magie volontairement ajoutés.\nExemples de Spécialisation : par type de support"),
  contrefacon(title: "Contrefaçon", family: SkillFamily.technique, reservedCastes: [Caste.artisan, Caste.commercant], description: "Permet de créer des répliques exactes de tout type d'objets, documents officiels, monnaies ou parchemins, mais aussi de les modifier en vue de les rendre authentiques. La falsification dobjets ou de textes spécifiques nécessite une connaissance précise du sujet.\nCette Compétence est réservée est réservée aux artisans et aux commerçants.\nExemples de Spécialisation : documents officiels, sceaux et poinçons, bijoux, monnaies, signatures, etc."),
  discretion(title: "Discrétion", family: SkillFamily.technique, description: "Permet de se déplacer en évitant d'attirer l'attention de son entourage. Elle permet aussi bien de prendre garde aux sons, au champ de vision d'un observateur, mais aussi de surveiller son ombre portée et les reflets de son équipement.\nExemples de Spécialisation : se dissimuler dans l'ombre, de déplacer silencieusement, etc."),
  enchantement(title: "Enchantement", family: SkillFamily.technique, reservedCastes: [Caste.mage], description: "Permet de conférer à un objet la faculté de déclencher un sortilège connu du personnage. Pour cela, il faut tout d'abord réussir un jet de Mental + Enchantement contre une Difficulté de 10 + 5 par Niveau du sortilège employé, puis effectuer le jet correspondant au lancement du sortilège. Toutes les conditions nécessaire à l'incantation doivent être réunies au moment de l'enchantement, y compris les Points de Magie, que le personnage doit impérativement dépenser. Une fois enchanté, l'objet pourra déclencher le sortilège sans avoir besoin de Points de Magie, exceptés ceux permettant d'augmenter la portée, la durée ou les effets du sort, qui restant à la charge de l'utilisateur.\nSi le mage le désire, il peut augmenter de 5 la Difficulté du premier jet d’enchantement pour permettre à un autre personnage d’utiliser l’objet. Dans ce cas, il n’est pas nécessaire de nommer le bénéficiaire, mais ce dernier devra connaître la Clé de déclenchement indispensable, et ce sont les caractéristiques magiques de l’enchanteur qui seront utilisées pour gérer le déclenchement.\nUn même objet ne peut être enchanté que par un seul sortilège à la fois. L’enchantement prend 1 heure + 1 par Niveau du sortilège impliqué, mais le sortilège reste gravé sans limite de durée.\nChaque objet enchanté ne peut servir qu’une fois et doit être ré-enchanté après usage. L'activation de l'objet demande une action et les effets du sorts sont immédiatement résolus.Exemples de Spécialisation : par type de support."),
  mecanismes(title: "Mécanismes", family: SkillFamily.technique, forbidden: true, description: "Permet de comprendre, de construire et d'utiliser efficacement des mécanismes tels que les roues, les engrenages, les ressorts, les poulies et les autres inventions typiquement humaines. Cette Compétence n'est pas interdite, mais certaines de ses applications − comme les armes mécaniques ou les instruments de mesure maritime − sont considérées comme hérétiques par les Grands Dragons et leurs représentants.\nMécanismes s'utilise généralement avec l'Attribut Manuel. Le niveau de cette Compétence ne peut pas dépasser la Tendance Homme du personnage + 5.\nExemples de Spécialisation : engrenages, mécanismes à ressort, mécanismes à poulie, etc."),
  pieges(title: "Pièges", family: SkillFamily.technique, reservedCastes: [Caste.artisan, Caste.voyageur], description: "Permet de confectionner, de poser, d'utiliser et de désarmorcer des dièges allant du simple collet au piège articulé comme les pieux à balayage ou les chausse-trappes.\nCette Compétence est réservée aux artisans et aux voyageurs.\nExemples de Spécialisation : pièges à ficelle, pièges à bascule, pièges à gros gibier, etc."),
  pister(title: "Pister", family: SkillFamily.technique, description: "Permet de repérer, d'interpréter et de suivre des traces. Il est aussi possible de dater les différentes traces, de déterminer le gabarit de la personne ou de l'animal. Il n'est pas possible de pister dans les cités. La Compétence Pister s'utiliser généralement directement avec la Perception, et avec Manuel lursqu'il s'agit d'examiner une zone : chercher des traces sans les masquer avec les siennes, rechercher des branches cassées, des feuilles déplacées.\nExemples de Spécialisation : traces de gros gibier, repérages militaires, pistage de caravanes, etc."),
  pyrotechnie(title: "Pyrotechnie", family: SkillFamily.technique, reservedCastes: [Caste.mage], description: "Cette Compétence est réservée aux Mages du Feu.\nÀ ne pas confondre avec Explosif, puisque le magicien n'utilise pas de poudre, mais sa magie. Les feux d'articife sont innoffensifs et ne font pas peur au commun des mortels. Suivant le temps de préparation, le pyrotechnicien pourra faire varier les tailles et les couleurs. La différence avec le sortilège “Conflagration écarlate” tient au fait qu'on ne dépense ici aucun Point de Magie, mais seulement du temps, et que les utilisations sont beaucoup plus “théâtrales”.\nImpose de posséder la Sphère du Feu à 3. Le personnage doit encore posséder un point de magie de feu pour pouvoir créer des illusions ignées.\n Exemple de Spécialisation : par type de spectacle."),
  reparation(title: "Réparation", family: SkillFamily.technique, reservedCastes: [Caste.combattant], description: "Permet au personnage d'effectuer des réparations rapides, mais efficaces, sur n'importe quelle arme ou armure, ainsi que sur le matériel d'équipement d'un cheval − s'il possède la Compétence Équitation. Il faut pour cela réussir un jet de Manuel + Réparation contre une Difficulté de 10 à la base, augmentée par le degré d'usure de l'objet − son pourcentage de perte, en rapport avec les dommages subis. La Difficulte est augmentée de 5 si l'objet est détruit au quart, de 10 pour la moité et de 15 pour les trois-quarts. Un objet entièrement détruit ne peut être concerné par cette Compétence. Si le jet est réussi, l'objet récupère un quart de sa fraîcheur pour chaque Niveau de Réussite obtenu. Une armure réparée avec cette Compétence au lieu de l'Artisanat nécessaire ne peut être réparée qu’une fois et regagne un point de protection par NR (après quoi l’action d’un artisan compétent est nécessaire).\nExemples de Spécialisation : par type de matériel."),
  sabotage(title: "Sabotage", family: SkillFamily.technique, reservedCastes: [Caste.artisan], description: "Permet au personnage de trouver le point faible d'un objet, d'un édifice ou de toute construction humaine, en vue de la détruire ou de lui infliger des dommages spécifiques. Il appartient au meneur de jeu de déterminer la Difficulté d'un jet de Sabotage, en tenant compte de la solidité et de la complexité de la structure visée.\nIl faut posséder au moins 1 dans la Compétence liée à l'objet ciblé pour le saboter.\nExemples de Spécialisation : par type d'objet ou de structure."),

  // Manipulation
  armesAPoudreNoire(title: "Armes à poudre noire", family: SkillFamily.manipulation, forbidden: true, description: "Cette Compétence est l'une des pires qui puissent être développées par les Humanistes. Quasiment inconnue (même de réputation) dans les terres draconistes, elle permet d'utiliser les couveuvrines et les arquebuses créées par les Humanistes il y a quelques années.\nLorsqu'un personnage utilise la poudre noire (que ce soit avec Explosifs, Armes à poudre noire ou encore dans le cas des Armes de siège), il peut choisir d'utiliser ou non les Tendance. S'il les utilise, la poudre explose de façon incontrôlée si les trois dés indiquent le même résultat (triple 1, triple 2, etc.). S'il ne les utilise pas, la poudre peut exploser lors d'un échec critique. Le personnage voit alors toute la poudre noire dans un rayon d'un mètre exploser subitement. Selon la quantité mise en œuvre, le meneur jugera des blessures, des mutilations ou du décès de l'infortuné artificier.\nIl est impossible pour le moment de développer cette Compétence sans posséder l'Avantage Humaniste. Le niveau de cette COmpétence ne peut dépasser la Tendance Homme du personnage + 5.\nExemples de Spécialisation : aucune."),
  armesAProjectiles(title: "Armes à projectiles", family: SkillFamily.manipulation, reservedCastes: [Caste.voyageur], description: "Permet de connaître et de manier les armes à projectiles (arcs, frondes, etc.) Cette catégorie d'armes n'est absolument pas interdite, mais seulement la caste des voyageurs est officiellement autorisée à utiliser les armes à projectiles. Tous les autres personnages s'exposent à des sanctions ou, dans le meilleur des cas, à la mauvaise considération de leur entourage. Tous les jets de tire s'effectuent avec l'Attribut Manuel.\nCette Compétence est réservée aux voyageurs.\nExemples de Spécialisation : par arme."),
  attelages(title: "Attelages", family: SkillFamily.manipulation, description: "Permet de diriger et de conduire des convois utilisant des animaux, des roulottes et des véhicules du même type, mais aussi d'en organiser efficacement la défense ou do procéder à des opérations d'entretien.\nExemples de Spécialisation : chars de guerre, chariots de transport, charrettes paysannes, etc."),
  crochetage(title: "Crochetage", family: SkillFamily.manipulation, description: "Permet de manipuler à l’aide de petits instruments les serrures mécaniques inventées par les Humanistes. Sans être interdite, cette Compétence est quasiment inconnue dans les terres draconistes étant donné son inutilité face aux loquets des artisans draconistes. Elle n’est en effet utilisée que par les voleurs nésoriens pour ouvrir les portes des riches demeures de leurs terres. Cette Compétence peut remplacer Déverrouillage pour ouvrir les loquets draconistes, mais ne permet pas d’obtenir de NR, quel que soit son jet. En effet, si le principe est similaire, il est loin d’être identique. Il convient de consulter les règles sur ces équipements pour bien comprendre les limites de cette Compétence. Il est impossible d’utiliser Déverrouillage pour remplacer Crochetage.\nLe niveau de cette Compétence ne peut dépasser la Tendance Homme du personnage + 5.\nExemples de Spécialisation : par type de serrure."),
  deguisement(title: "Déguisement", family: SkillFamily.manipulation, description: "Permet de modifier son apparence pour ressembler à n'importe quel individu. Cette Compétence ne permet qu'une modification restreinte de la taille et de la corpulence du personnage. Cette Compétence peut également être tulisisée pour “maquiller” un objet.\nExemples de Spécialisation : changer de sexe, changer son âge, etc."),
  deverrouillage(title: "Déverrouillage", family: SkillFamily.manipulation, reservedCastes: [Caste.artisan, Caste.commercant], description: "Permet de venir à bout de n'importe quel type de fermeture et de forcer le déclenchement de mécanismes.\nCette Compétence est réservée aux artisans et aux commerçants.\nExemples de Spécialisation : verrous, loquets, etc."),
  donArtistique(title: "Don artistique", family: SkillFamily.manipulation, requireConcreteImplementation: true, description: "Permet de pratiquer des arts tels que la sculpture, la peinture ou de jouer d'un instrument musical. Cette Compétence est utilisée avec l'Attribut Manuel.\nExemples de Spécialisation : par instrument, sculpture (sur bois), peinture (fresques), peinture (tableaux), etc."),
  faireLesPoches(title: "Faire les poches", family: SkillFamily.manipulation, reservedCastes: [Caste.commercant, Caste.voyageur], description: "Permet de faire les poches, de voler ou d'escamoter et de dissimuler de petits objets sur soi (tant que l'on dispose de vêtements un peu amplase).\nCette Compétence est réservée aux commerçants et aux voyageurs.\nExemples de Spécialisation : par type de larcin (vol à l'étalage, vol de bourses, etc.)"),
  imitation(title: "Imitation", family: SkillFamily.manipulation, reservedCastes: [Caste.mage], description: "Cette compétence est uniquement accessible aux Mages des Cités qui ont le désavantage “Mauvaise réputation”.\nCette Compétence ne peut s’utiliser que s’il reste au personnage au moins un point de magie en Sphère des cités.\nElle permet d’imiter à la perfection la voix d’une personne, même écoutée une seule fois. Chaque NR obtenu sur un jet permet de berner une personne de plus. La Difficulté du jet dépend de la connaissance qu’a le public de la personne imitée (de 10 pour quelqu’un connu de vue à 30 pour un membre de la famille). Elle n’influe plus en rien sur les mimiques ou le déguisement (qui sont gérés par d’autres Compétences)."),
  jeu(title: "Jeu", family: SkillFamily.manipulation, description: "Permet de connaître les règles et les astuces des différents jeux pratiqués sur le monde (jeux de dés, de cartes, de pions).\nExemples de Spécialisation : par jeu (cartes ankariennes, dés menteurs jasporiens, etc.)"),
  jongler(title: "Jongler", family: SkillFamily.manipulation, description: "Permet de manipuler des objets en vue d'effectuer des figures artistiques ou des tours de passe-passe.\nExemples de Spécialisation : par accessoire (quilles, brandons, balles, etc.)"),
  machinesVolantes(title: "Machines volantes", family: SkillFamily.manipulation, forbidden: true, description: "Permet de piloter et d'entretenir les appareillages volants bricolés par les inventeurs Humanistes. Il est possible de piloter un deltaplane, d'utiliser une voile de parapente ou de se servir d'un ballon à air chaud. Il convient de consulter les règles sur ces équipements pour bien comprendre les limites de cette Compétence.\nExemples de Spécialisation : par appareil."),
  magnetisme(title: "Magnétisme", family: SkillFamily.manipulation, reservedCastes: [Caste.mage], description: "Cette compétence est uniquement accessible aux Mages du Métal qui ont le désavantage “Malédiction de Kezyr”.\nEn réussissant un jet contre une Difficulté de 15 et en dépensant deux Points de magie de la Sphère du Métal, le mage peut fabriquer un aimant dont la puissance est proportionnelle au Niveau de Réussite.\n- 0NR : peut faire bouger une pièce\n- 1NR : peut faire bouger un petit trousseau de clés\n- 2NR : peut faire bourge une dague ou une petite lame\n- etc."),
  manipulationDesPierresIrradiantes(title: "Manipulation des pierres irradiantes", family: SkillFamily.manipulation, reservedCastes: [Caste.mage], description: "Cette Compétence est uniquement accessible aux Mages de la Pierre formés dans un Creuset et avec le Désavantage “Interdits de Brorne”.\nCette Compétence, réservée aux magiciens issus d’un Creuset, est partagée avec les mages de Kalimsshar. La découverte des pierres irradiantes est assez récente (cent ans au plus). Ce ne sont que de simples cailloux légèrement luminescents qui se trouvent très profondément enfouis sous terre. Ils sont chauds au contact et laissent des marques sur la peau comme s’ils la brûlaient. Les premiers mineurs qui les trouvèrent furent pris de malaise et succombèrent rapidement, couverts de cloques. Des magiciens furent dépêchés sur place et découvrirent que ces pierres contenaient une réserve naturelle de magie. Ils décidèrent de les scinder et d’en orner des amulettes, des bijoux ou des objets enchantés.\nCes pierres contiennent des points de magie non utilisables. Elles fournissent des bonus de +1 à +10. Maîtriser cette compétence permet de lancer des sortilèges avec le bonus de la pierre ajouté à l’une des trois Disciplines (la Sorcellerie est la plus courante), à la condition d’ajouter dans les Clés un éclat de pierre irradiante. À chaque usage, le magicien devra faire un jet de Manuel + Manipulation des pierres irradiantes contre une Difficulté de (15 + Bonus de la pierre) avant de lancer le sort. S’il échoue, il perdra définitivement une case d’Égratignure.\nExemples de Spécialisation : par Discipline."),
  maitriseDesIncendies(title: "Maîtrise des incendies", family: SkillFamily.manipulation, reservedCastes: [Caste.mage], description: "Cette Compétence est réservée aux Mages du Feu.\nIl n'est pas rare qu'un magicien soit chargé de surveiller les incendies éventuels dans les grandes cités. Cette Compétence sert à anticiper les mouvements du feu, son étalement et la méthode à adopter pour les arrêter. Idéal aussi pour savoir par où sortir d'un bâtiment ou d'une forêt en feu. C'est le métier qui permet un rapprochement, sinon une franche coopération, entre les mages d'Ozyr et de Kroryn. À plus petite échelle, cela permet de savoir allumer un feu sous une pluie battante.\nExemples de Spécialisation : par type de feu (forêt, maison, huile, etc.)"),
  torture(title: "Torture", family: SkillFamily.manipulation, reservedCastes: [Caste.combattant], description: "Permet au personnage d'user de la force − et de la faiblesse − de sa victime pour soutirer des informations. C'est un jet d'opposition avec Manuel ou Physique (selon la méthode) + Torture contre Volonté + Résistance de la cible. Les modificateurs peuvent s’appliquer pour les conditions de détention, l’usage de matériel éprouvé ou la pression morale. Chaque jet inflige une blessure à la cible (en commençant par les Égratignures). Le personnage peut obtenir une information par Niveau de Réussite, mais la plupart des victimes ainsi torturées préfèrent généralement tout avouer…\nIl va sans dire que de telles pratiques s'accompagnent d'un gain immédiat de Cercles de Fatalité.\nExemples de Spécialisation : par méthode."),

  // Communication
  baratin(title: "Baratin", family: SkillFamily.communication, description: "Permet de prendre l'ascendant lors d'une discussion pour faire aboutir rapidement son point de vue.\nExemples de Spécialisation : flatterie, jargon technique, etc."),
  ceremonie(title: "Cérémonie", family: SkillFamily.communication, reservedCastes: [Caste.mage], description: "Cette compétence est uniquement accessible aux Mages des Océans qui ont le désavantage “Instinct supérieur”, ou aux Prodiges, protecteurs ou paladins membres de la Loge Théologique (qui n'ont pas besoin de posséder le désavantage).\nCette Compétence dénote une connaissance approfondie des rituels, prières et actes de foi concernant la vénération d'Ozyr, sujette à des protocoles complexes. Elle permet de connaître les rites quotidiens et les cérémonies nuptiales, mortuaires et de naissance. Elle permet de conduire des prières qui motiveront la foi des fidèles. Selon la Difficulté de la cérémonie et les circonstances, le mage peut affecter 10 foix sa Tendance Dragon en auditeurs, leur conférant un bonus égal au Statut de l'officiant le plus élevé, qui s'ajoutera à tout jet visant à confirmer la foi d'un fidèle face et aux tentation hérétiques."),
  conte(title: "Conte", family: SkillFamily.communication, reservedCastes: [Caste.erudit, Caste.voyageur], description: "Permet d'inventer et de raconter des histoires en vue de susciter des réactions dans son public. Un bon jet peut fortement influencer le moral du public, effrayer les enfants, provoquer l'admiration et accroître sa Renommée de manière temporaire d'un ou deux points.\nCette Compétence est réservée aux érudits et aux voyageurs.\nExemples de Spécialisation : ballades héroïques, histoires infantiles, etc."),
  eloquence(title: "Éloquence", family: SkillFamily.communication, description: "Permet de prendre la parole devant une foule, de modules ses rpactions et de faire prévaloir un sentiment commun (colère, joie, calme, recueillement, etc.)\nExemples de Spécialisation : par type de public (troupes, bas peuple, conseils politiques, etc.)"),
  marchandage(title: "Marchandage", family: SkillFamily.communication, reservedCastes: [Caste.artisan, Caste.commercant], description: "Permet de négocier avantageusement le prix de vente ou d'achat d'une marchandise, ainsi que les conditions d'un marché.\nChaque Niveau de Réussite sur le jet d'opposition permet d'obtenir un bonus de 10% en sa faveur.\nCette Compétence est réservée aux artisans et aux commerçants.\nExemples de Spécialisation : par marchandise (épices, armes, montures, chariots, etc.)"),
  psychologie(title: "Psychologie", family: SkillFamily.communication, description: "Permet de comprendre les motivations, d'analyser les émotions et danticiper le comportement d'un être humain. Elle peut également être utilisée sur des créatures intelligentes, mais la Difficulté de tous les jets sera augmentée de 5.\nExemples de Spécialisation : observation à distance, discussion analytique, sur les hommes, sur les femmes, etc."),
  usurpation(title: "Usurpation", family: SkillFamily.communication, reservedCastes: [Caste.commercant], description: "Cette Compétence permet de simuler le comportement et l’attitude d’une personne précise, alors que le Déguisement va imiter son apparence. La Difficulté du jet est de 10 à la base et peut être augmentée de 5 à 20, en faction de la réputation de la personne ainsi mystifiée, d'une éventuel changement de sexe ou d'une particularité physique inimitable − handicap, aura magique, etc. Une ressemblanc naturelle ou des dons magiques peuvent au contraire diminuer cette Difficulté. Elle s’accompagne souvent d’une étude préliminaire en Psychologie et peut bénéficier de dons d’artiste venus des Arts de la scène (ces deux Compétences octroyant alors des bonus indirects au jet d’Usurpation)."),

  // Influence
  artDeLaScene(title: "Art de la scène", family: SkillFamily.influence, requireConcreteImplementation: true, description: "Permet de maîtriser les différentes technique d'un domaine artistique lié au verbe et au corps te que la dans, le chant, le théâtre, etc. Il est impératif de développer une Spécialisation pour chaque type d'art.\nCette compétence est enseignée dans les écoles de magie afin de évelopper les postures et les chants nécessaires au lancement de sorts.\nExemples de Spécialisation : danse (de cour), danse (tribale), chant (polyphonies), etc."),
  chantsOniriques(title: "Chants oniriques", family: SkillFamily.influence, reservedCastes: [Caste.mage], description: "Cette compétence est est uniquement accessible aux Mages des Rếves avec le désavantage “Marque de Nenya” ou aux Ménestrels de Szyl.\nCette Compétence permet au mage - accompagné ou non par de la musique - de subjuguer un auditoire par son chant. Mélange de mélancolie, de féerie et de voyage, la mélopée peut apaiser les guerriers les plus ivres. Le mage peut aussi l'utiliser pour accompagner quelqu’un dans la mort ou calmer un animal. Ces chants s'utilisent par un jet d'Opposition contre Social + Volonté de la cible. Le Chant des Ombres de Szyl est une application directe de cette Compétence. Elle est donc acessible aux Ménestrels de Szyl. Souvent utilisé pour calmer un individu en furie, le chant peut aussi apporter la joie, l'espoir ou encore le courage.\nExemple de Spécialisation: par type de chant (chant des ombres, chant funèbre, chant de joie)."),
  commandement(title: "Commandement", family: SkillFamily.influence, reservedCastes: [Caste.combattant, Caste.protecteur], description: "Permet de donner des ordres et de s'assurer qu'ils seront suivis, mais aussi d'sur de sa Présence pour prendre la direction d'un groupe.\nCette Compétence est réservée aux combattants et aux protecteurs.\nExemples de Spécialisation : par type d'unités (escouades de milice, patrouilles rurales, etc.)"),
  diplomatie(title: "Diplomatie", family: SkillFamily.influence, description: "Permet de conclure toutes sortes de marchés, d'alliances, de pactes et d etraités, mais aussi de modifier son comportement en vue de s'attirer des faveurs et darbitrer des discussions difficiles.\nExemples de Spécialisation : traités de paix, chartes commerciales, litiges familiaux, etc.)"),
  domination(title: "Domination", family: SkillFamily.influence, reservedCastes: [Caste.mageNoir], description: "Cette compétence est réservée aux Mages de l'Ombre.\nCette Compétence représente une capacité à se faire reconnaître des créatures de l’Ombre et à s’en faire parfois obéir, ce qui induit une sorte d’immunité. Le mage confronté à une créature de l’Ombre effectue un jet de Social + Domination contre une Difficulté égale à Volonté x 3 de la cible. Si le jet est réussi, la créature reconnaît un Augure Noir et le laisse tranquille. Avec un Niveau de Réussite, la créature consent à ignorer les compagnons de l'Augure, jusqu'à un par Point de Présence. Avec deux Niveaux de Réussite, la créature est partiellement soumise et l’Augure peut lui donner un ordre mineur (pas plus d’une demi-heure de résolution)."),
  dressage(title: "Dressage", family: SkillFamily.influence, reservedCastes: [Caste.artisan, Caste.prodige, Caste.voyageur], description: "Permet d'apprendre des tours à des animaux domestiques, de dresser des animaux sauvages et d'anticiper le comportement d'un animal lorsque l'on se trouve en sa présence. La Difficulté des jets dépend à la fois de l'espèce de l'animal et du comportement que le personnage tente de lui imposer.\nCette Compétence est réservée aux artisans, aux Prodiges et aux voyageurs.\nExemples de Spécialisation : par type d'animaux (poissons, rongeurs, félins, etc.), tours de foire, etc."),
  enseignement(title: "Enseignement", family: SkillFamily.influence),
  hypnose(title: "Hypnose", family: SkillFamily.influence, description: "Découverte depuis des années par les philosophes humanistes, cette Compétence fut le premier jalon de ce qui devait devenir les Pouvoirs de l’esprit. S’appuyant sur le pouvoir de suggestion issu de leur “force mentale”, les Humanistes ont réussi à mettre au point cet art qui reste encore, dans les terres draconistes, assimilé à la magie des saltimbanques. Souvent sous-estimée, l’hypnose ne fonctionne que sure une cible statique dont on parvient à capter le regard durant au moins un tour complet. Cette Compétence est délicate et peu puissante, mais elle est indétectable et parfois déroutante. Capter le regard d’une cible se résout par un jet d’Opposition de Social + Hypnose contre Mental + Volonté de la cible, effectué à la fin du tour complet de scrutation. Si le jet est réussi, la cible est réceptive et peut révéler des souvenirs conscients ou inconscients (mais pas des secrets) par un jet d’une Difficulté de 20. Elle peut également être maintenue immobile ou muette (Difficulté 20), être endormie (Difficulté 25, 5 actions) ou subir une suggestion hypnotique (Difficulté 30, plusieurs minutes). Il n’est pas possible de mettre la cible en danger par l’une ou l’autre de ces manipulations, ceci brisant la réceptivité. Les victimes se souviennent de ce qui leur a été dit ou de ce qu’elles ont fait sous cette transe, mais disent ne pas avoir pu agir ou refuser. Il n’est pas possible de modifier la mémoire par ce biais, mais certaines barrières morales peuvent tomber sous hypnose.\nToute utilisation d’Hypnose coûte un point de Ferveur par tour, une suggestion hypnotique coûtant de plus un point par jour d’activité. Utilisée préliminairement à un pouvoir de l’esprit classé comme Mental, l’hypnose s’utilise par un jet de Difficulté 10 consécutif à l’établissement du contact visuel et dont chaque NR apporte un bonus indirect do +1 à l’utilisation du pouvoir.\nExemples de Spécialisation : par type de focus (voix, pendule, chanson, …)"),
  interrogatoire(title: "Interrogatoire", family: SkillFamily.influence, reservedCastes: [Caste.protecteur], description: "Permet de mener un interrogatoire en utilisant diverses techniques d’intimidation, de stress, de pression psychologique ou physique, de torture, etc. Comparable aux Compétences Torture et Intimidation, c'est un jet d'opposition avec Mental, Manuel ou Physique (selon la méthode) + Torture contre Volonté + Résistance de la cible. Les modificateurs peuvent s’appliquer pour les conditions de détention, l’usage de matériel éprouvé ou la pression morale. Le personnage peut obtenir une information par jet, plus une par Niveau de Réussite.\nSi elle reste l’apanage des protecteurs, c’est parce qu’elle n’expose son utilisateur à aucun désagrément - en effet, si la torture est mal vue, les interrogatoires en règle sont monnaie courante dans la vie des Inquisiteurs…Exemples de Spécialisations : par méthode."),
  intimidation(title: "Intimidation", family: SkillFamily.influence, description: "Permet d'influencer le comportement d'un homme ou d'une créature en utilisant la menace, la force ou simplement l'image que l'on donne de soi, etc.\nExemples de Spécialisation : intimidation verbale, intimidation par le regard, etc."),
  seduction(title: "Séduction", family: SkillFamily.influence, description: "Permet de jouer sur les sentiments et les émotions pour s'attirer les faveurs d'un membre du sexe opposé.\nExemples de Spécialisation : séduction stylée, attirance animale, amour courtois, etc."),
  ;

  const Skill({
    required this.title,
    required this.family,
    this.requireConcreteImplementation = false,
    this.canInstantiate = true,
    this.reservedCastes = const <Caste>[],
    this.description = '',
    this.forbidden = false,
  });

  static List<Skill> fromFamily(SkillFamily family, {Caste? forCaste}) {
    List<Skill> ret = <Skill>[];
    for(var s in Skill.values) {
      if(
      s.family == family
          && (
          forCaste == null
              || s.reservedCastes.isEmpty
              || s.reservedCastes.contains(forCaste)
      )
      ) {
        ret.add(s);
      }
    }
    return ret;
  }

  static Skill? byTitle(String descr) {
    Skill? ret;
    for(var s in Skill.values) {
      if(s.title == descr) ret = s;
    }
    return ret;
  }

  final String title;
  final SkillFamily family;
  final bool requireConcreteImplementation;
  final bool canInstantiate;
  final List<Caste> reservedCastes;
  final String description;
  final bool forbidden;
}
