// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'specialized_skill.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SpecializedSkill _$SpecializedSkillFromJson(Map<String, dynamic> json) =>
    SpecializedSkill.create(
      parent: $enumDecode(_$SkillEnumMap, json['parent']),
      name: json['name'] as String,
      reserved: json['reserved'] as bool? ?? false,
      reservedPrefix: json['reserved_prefix'] as String?,
      reservedCastes:
          (json['reserved_castes'] as List<dynamic>?)
              ?.map((e) => $enumDecode(_$CasteEnumMap, e))
              .toList() ??
          const <Caste>[],
    );

Map<String, dynamic> _$SpecializedSkillToJson(SpecializedSkill instance) =>
    <String, dynamic>{
      'parent': _$SkillEnumMap[instance.parent]!,
      'name': instance.name,
      'reserved': instance.reserved,
      'reserved_prefix': instance.reservedPrefix,
      'reserved_castes': instance.reservedCastes
          .map((e) => _$CasteEnumMap[e]!)
          .toList(),
    };

const _$SkillEnumMap = {
  Skill.armesArticulees: 'armesArticulees',
  Skill.armesContondantes: 'armesContondantes',
  Skill.armesDeChoc: 'armesDeChoc',
  Skill.armesDeJet: 'armesDeJet',
  Skill.armesDoubles: 'armesDoubles',
  Skill.armesDHast: 'armesDHast',
  Skill.armesTranchantes: 'armesTranchantes',
  Skill.bouclier: 'bouclier',
  Skill.corpsACorps: 'corpsACorps',
  Skill.criDeLaPierre: 'criDeLaPierre',
  Skill.creatureNaturalWeapon: 'creatureNaturalWeapon',
  Skill.acrobatie: 'acrobatie',
  Skill.athletisme: 'athletisme',
  Skill.combatMonte: 'combatMonte',
  Skill.endurance: 'endurance',
  Skill.equitation: 'equitation',
  Skill.escalade: 'escalade',
  Skill.esquive: 'esquive',
  Skill.natation: 'natation',
  Skill.torture: 'torture',
  Skill.anticipationDesOrages: 'anticipationDesOrages',
  Skill.castes: 'castes',
  Skill.conception: 'conception',
  Skill.connaissanceDeLaMagie: 'connaissanceDeLaMagie',
  Skill.connaissanceDesAnimaux: 'connaissanceDesAnimaux',
  Skill.connaissanceDesDragons: 'connaissanceDesDragons',
  Skill.connaissanceDeLaPierre: 'connaissanceDeLaPierre',
  Skill.facture: 'facture',
  Skill.fauneEtFlore: 'fauneEtFlore',
  Skill.geographie: 'geographie',
  Skill.histoire: 'histoire',
  Skill.interpretationDesReves: 'interpretationDesReves',
  Skill.lois: 'lois',
  Skill.necromancie: 'necromancie',
  Skill.orientation: 'orientation',
  Skill.perceptionClimatique: 'perceptionClimatique',
  Skill.strategie: 'strategie',
  Skill.alchimie: 'alchimie',
  Skill.analyse: 'analyse',
  Skill.astrologie: 'astrologie',
  Skill.cartographie: 'cartographie',
  Skill.cartographierLesReves: 'cartographierLesReves',
  Skill.chirurgie: 'chirurgie',
  Skill.estimation: 'estimation',
  Skill.explosifs: 'explosifs',
  Skill.explosifsDeBrorne: 'explosifsDeBrorne',
  Skill.herboristerie: 'herboristerie',
  Skill.investigation: 'investigation',
  Skill.jardinage: 'jardinage',
  Skill.langageDesAnimaux: 'langageDesAnimaux',
  Skill.langageDesPlantes: 'langageDesPlantes',
  Skill.langueDesSignes: 'langueDesSignes',
  Skill.lireEtEcrire: 'lireEtEcrire',
  Skill.matieresPremieres: 'matieresPremieres',
  Skill.medecine: 'medecine',
  Skill.meditation: 'meditation',
  Skill.premiersSoins: 'premiersSoins',
  Skill.psychometrie: 'psychometrie',
  Skill.soinsOniriques: 'soinsOniriques',
  Skill.survie: 'survie',
  Skill.toucheDePerfection: 'toucheDePerfection',
  Skill.vieEnCite: 'vieEnCite',
  Skill.vieEnForet: 'vieEnForet',
  Skill.armesDeSiege: 'armesDeSiege',
  Skill.armesMecaniques: 'armesMecaniques',
  Skill.armure: 'armure',
  Skill.artisanat: 'artisanat',
  Skill.contrefacon: 'contrefacon',
  Skill.discretion: 'discretion',
  Skill.enchantement: 'enchantement',
  Skill.mecanismes: 'mecanismes',
  Skill.pieges: 'pieges',
  Skill.pister: 'pister',
  Skill.pyrotechnie: 'pyrotechnie',
  Skill.reparation: 'reparation',
  Skill.sabotage: 'sabotage',
  Skill.armesAProjectiles: 'armesAProjectiles',
  Skill.attelages: 'attelages',
  Skill.deguisement: 'deguisement',
  Skill.deverrouillage: 'deverrouillage',
  Skill.donArtistique: 'donArtistique',
  Skill.faireLesPoches: 'faireLesPoches',
  Skill.imitation: 'imitation',
  Skill.jeu: 'jeu',
  Skill.jongler: 'jongler',
  Skill.magnetisme: 'magnetisme',
  Skill.manipulationDesPierresIrradiantes: 'manipulationDesPierresIrradiantes',
  Skill.maitriseDesIncendies: 'maitriseDesIncendies',
  Skill.baratin: 'baratin',
  Skill.ceremonie: 'ceremonie',
  Skill.conte: 'conte',
  Skill.eloquence: 'eloquence',
  Skill.marchandage: 'marchandage',
  Skill.psychologie: 'psychologie',
  Skill.artDeLaScene: 'artDeLaScene',
  Skill.chantsOniriques: 'chantsOniriques',
  Skill.commandement: 'commandement',
  Skill.diplomatie: 'diplomatie',
  Skill.domination: 'domination',
  Skill.dressage: 'dressage',
  Skill.enseignement: 'enseignement',
  Skill.interrogatoire: 'interrogatoire',
  Skill.intimidation: 'intimidation',
  Skill.seduction: 'seduction',
};

const _$CasteEnumMap = {
  Caste.sansCaste: 'sansCaste',
  Caste.artisan: 'artisan',
  Caste.combattant: 'combattant',
  Caste.commercant: 'commercant',
  Caste.erudit: 'erudit',
  Caste.mage: 'mage',
  Caste.prodige: 'prodige',
  Caste.protecteur: 'protecteur',
  Caste.voyageur: 'voyageur',
};
