// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'skill_instance.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SkillInstance _$SkillInstanceFromJson(Map<String, dynamic> json) =>
    SkillInstance(
      skill: $enumDecode(_$SkillEnumMap, json['skill']),
      value: (json['value'] as num).toInt(),
      implementation: json['implementation'] as String?,
    );

Map<String, dynamic> _$SkillInstanceToJson(SkillInstance instance) =>
    <String, dynamic>{
      'skill': _$SkillEnumMap[instance.skill]!,
      'value': instance.value,
      'implementation': instance.implementation,
    };

const _$SkillEnumMap = {
  Skill.armesArticulees: 'armesArticulees',
  Skill.armesContondantes: 'armesContondantes',
  Skill.armesDeChoc: 'armesDeChoc',
  Skill.armesDeJet: 'armesDeJet',
  Skill.armesDoubles: 'armesDoubles',
  Skill.armesDHast: 'armesDHast',
  Skill.armesTranchantes: 'armesTranchantes',
  Skill.bouclier: 'bouclier',
  Skill.corpsACorps: 'corpsACorps',
  Skill.criDeLaPierre: 'criDeLaPierre',
  Skill.creatureNaturalWeapon: 'creatureNaturalWeapon',
  Skill.acrobatie: 'acrobatie',
  Skill.athletisme: 'athletisme',
  Skill.cavalerieAerienne: 'cavalerieAerienne',
  Skill.combatMonte: 'combatMonte',
  Skill.endurance: 'endurance',
  Skill.equitation: 'equitation',
  Skill.escalade: 'escalade',
  Skill.esquive: 'esquive',
  Skill.natation: 'natation',
  Skill.anticipationDesOrages: 'anticipationDesOrages',
  Skill.castes: 'castes',
  Skill.chimie: 'chimie',
  Skill.conception: 'conception',
  Skill.connaissanceDeLaMagie: 'connaissanceDeLaMagie',
  Skill.connaissanceDesAnimaux: 'connaissanceDesAnimaux',
  Skill.connaissanceDesDragons: 'connaissanceDesDragons',
  Skill.connaissanceDeLaPierre: 'connaissanceDeLaPierre',
  Skill.facture: 'facture',
  Skill.fauneEtFlore: 'fauneEtFlore',
  Skill.geographie: 'geographie',
  Skill.histoire: 'histoire',
  Skill.interpretationDesReves: 'interpretationDesReves',
  Skill.lois: 'lois',
  Skill.mathematiques: 'mathematiques',
  Skill.necromancie: 'necromancie',
  Skill.orientation: 'orientation',
  Skill.philosophie: 'philosophie',
  Skill.physique: 'physique',
  Skill.perceptionClimatique: 'perceptionClimatique',
  Skill.strategie: 'strategie',
  Skill.alchimie: 'alchimie',
  Skill.analyse: 'analyse',
  Skill.astrologie: 'astrologie',
  Skill.cartographie: 'cartographie',
  Skill.cartographierLesReves: 'cartographierLesReves',
  Skill.chirurgie: 'chirurgie',
  Skill.estimation: 'estimation',
  Skill.explosifs: 'explosifs',
  Skill.explosifsDeBrorne: 'explosifsDeBrorne',
  Skill.forcesInvisible: 'forcesInvisible',
  Skill.herboristerie: 'herboristerie',
  Skill.investigation: 'investigation',
  Skill.jardinage: 'jardinage',
  Skill.langageDesAnimaux: 'langageDesAnimaux',
  Skill.langageDesPlantes: 'langageDesPlantes',
  Skill.langueDesSignes: 'langueDesSignes',
  Skill.lireEtEcrire: 'lireEtEcrire',
  Skill.matieresPremieres: 'matieresPremieres',
  Skill.medecine: 'medecine',
  Skill.meditation: 'meditation',
  Skill.oniromancie: 'oniromancie',
  Skill.premiersSoins: 'premiersSoins',
  Skill.psychometrie: 'psychometrie',
  Skill.soinsOniriques: 'soinsOniriques',
  Skill.survie: 'survie',
  Skill.toucheDePerfection: 'toucheDePerfection',
  Skill.vieEnCite: 'vieEnCite',
  Skill.vieEnForet: 'vieEnForet',
  Skill.armesDeSiege: 'armesDeSiege',
  Skill.armesMecaniques: 'armesMecaniques',
  Skill.armure: 'armure',
  Skill.artisanat: 'artisanat',
  Skill.artisanatElementaire: 'artisanatElementaire',
  Skill.contrefacon: 'contrefacon',
  Skill.discretion: 'discretion',
  Skill.enchantement: 'enchantement',
  Skill.mecanismes: 'mecanismes',
  Skill.pieges: 'pieges',
  Skill.pister: 'pister',
  Skill.pyrotechnie: 'pyrotechnie',
  Skill.reparation: 'reparation',
  Skill.sabotage: 'sabotage',
  Skill.armesAPoudreNoire: 'armesAPoudreNoire',
  Skill.armesAProjectiles: 'armesAProjectiles',
  Skill.attelages: 'attelages',
  Skill.crochetage: 'crochetage',
  Skill.deguisement: 'deguisement',
  Skill.deverrouillage: 'deverrouillage',
  Skill.donArtistique: 'donArtistique',
  Skill.faireLesPoches: 'faireLesPoches',
  Skill.imitation: 'imitation',
  Skill.jeu: 'jeu',
  Skill.jongler: 'jongler',
  Skill.machinesVolantes: 'machinesVolantes',
  Skill.magnetisme: 'magnetisme',
  Skill.manipulationDesPierresIrradiantes: 'manipulationDesPierresIrradiantes',
  Skill.maitriseDesIncendies: 'maitriseDesIncendies',
  Skill.torture: 'torture',
  Skill.baratin: 'baratin',
  Skill.ceremonie: 'ceremonie',
  Skill.conte: 'conte',
  Skill.eloquence: 'eloquence',
  Skill.marchandage: 'marchandage',
  Skill.psychologie: 'psychologie',
  Skill.usurpation: 'usurpation',
  Skill.artDeLaScene: 'artDeLaScene',
  Skill.chantsOniriques: 'chantsOniriques',
  Skill.commandement: 'commandement',
  Skill.diplomatie: 'diplomatie',
  Skill.domination: 'domination',
  Skill.dressage: 'dressage',
  Skill.enseignement: 'enseignement',
  Skill.hypnose: 'hypnose',
  Skill.interrogatoire: 'interrogatoire',
  Skill.intimidation: 'intimidation',
  Skill.seduction: 'seduction',
};
