enum SpiritPower {
  apaisement(title: "Apaisement", cost: 2, description: "Ce pouvoir Mental doit être utilisé au contact et permet d'apaiser l'esprit d'une personne. Un jet de Mental + Présence détermine l'ampleur des effets. À 15, il est possible de juguler une peur, une appréhension ou une phobie à 1. À 20, il est possible de juguler une peur surnaturelle ou résultant phobie à 3 ou à 5. À 25, on peut bloquer la douleur, mais la victime devient inerte et incapable de mouvements violents. À 30, la victime peut être plongée dans un sommeil profond et réparateur dont la durée dépend des conditions extérieures."),
  auraDePresence(title: "Aura de présence", cost: 3, description: "Ce pouvoir permet d'irradier littéralement un sentiment afin d'impressionner ses interlocuteurs. L'aura peut être au choix inquiétante, fascinante, innocente, séduisante, entêtante ou autre… Utiliser ce pouvoir nécessite un jet de Mental + Présence contre une Difficulté de 15 et fonctionne sur un nombre de cibles égal à son Empathie. Il est possible d'y résister par un jet de Mental + Volonté contre une Difficulté égale à 5 par point de Ferveur dépensé par l'utilisateur +1 / NR sur son jet. L'aura dure environ une heure."),
  barriereMentale(title: "Barrière mentale", cost: 4, description: "Ce pouvoir Mental est le seul qui puisse agir à l'encontre des intrusions mentales de tous types. Il permet de résister aux Pouvoir de l'esprit Mentaux et aux pouvoirs draconiques (Bénéfices, sorts, Faveurs, Privilèges…) visant à modifier l'esprit. Le personnage peut alors dépenser des points de Ferveur pour obtenir un bonus de +3/point sur un jet d'Opposition ou augmenter la Difficulté de l'action l'agressant de 3/point.\nCe pouvoir nécessite d'être conscient d'une attaque mentale (en possédant des Pouvoirs de l'esprit ou en ayant observé la capacité draconiste au moins une fois."),
  conviction(title: "Conviction", cost: 2, description: "Ce pouvoir permet de puiser dans sa force intérieure pour résister à la tentation et conserver son éthique. En dépensant un cercle de Tendance Homme et un point de Ferveur, le personnage peut éviter de gagner le(s) cercle(s) de Tendance Dragon ou Fatalité engendré(s) par une action. Il ne permet toutefois pas de contrer une perte éventuelle."),
  invasionMentale(title: "Invasion mentale", cost: 4, description: "Premier pouvoir découvert après l'hypnose, ce pouvoir Mental permet de ressentir les émotions d'une cible, d'accéder à son inconscient et de partager ses souvenirs. Il ne fonctionne que face à face et à moins de cinq mètres.\nUn jet d'une Difficulté de (5+Volonté de la cible) permet d'accéder aux émotions superficielles et de déceler une éventuelle duperie, une crainte ou une culpabilité (entre autres). Cette application coûte un point de Ferveur par tour.\nUn jet d'une Difficulté de (10+Volonté de la cible) permet d'accéder aux souvenirs et éventuellement de forcer la victime à les révéler. S'il s'agit d'un secret, il ne peut être révélé qu'après résolution d'un jet d'Opposition de Social+Volonté contre Mental+Volonté de la victime. Cette application coûte deux points de Ferveur par tour, plus un par jet d'Opposition engagé. Un jet contre une Difficulté de 20+Volonté de la cible permet de créer ou d'effacer des souvenirs. Cette manipulation se fait à raison d'un tour pour cinq minutes de souvenirs et coûte deux points de Ferveur par tour. "),
  lienSpirituel(title: "Lien spirituel", cost: 2, description: "Ce pouvoir Mental permet de placer une empreinte psychique sur une personne. Il est alors possible de la localiser (direction et temps de voyage approximatif) et de connaître le type de milieu où elle se trouve. En cas de danger, le personnage ressent également le sentiment majeur de sa cible (peur, confiance, douleur, fierté…). Ce pouvoir coûte un point de Ferveur tous les neuf jours et il est possible de maintenir autant de Liens que son Empathie. Son placement est automatique à moins que la cible ne soit pas consentante, auquel cas un jet d'Opposition en Mental+Empathie contre Mental+Volonté de la victime est nécessaire."),
  meditation(title: "Méditation", cost: 3, description: "Ce pouvoir permet de doubler les points gagnés lors d'une prière humaniste, qui sont alors de 2/NR sur le jet de Mental+Volonté de Difficulté 0. Les règles sur la durée et l'interruption de la prière ne sont pas modifiées."),
  negation(title: "Négation", cost: 5, description: "Spectaculaire, ce pouvoir permet de nier l'existence d'un phénomène surnaturel pour s'en prémunir. Le personnage peut ainsi nier l'existence d'un sort le visant, ce qui aura pour effet de distordre la réalité pour qu'il en soit protégé. Ce pouvoir n'annule pas le sort ou le phénomène, il ne fait qu'annuler les effets pour l'Humaniste.\nContre un sort, ce pouvoir coûte autant de points de Ferveur que le sort demande de points de magie et coûte une action. Le personnage doit réussir un jet de Mental+Volonté contre la Difficulté du sort+5/NR obtenu par le mage. Si le jet est manqué, les points de Ferveur sont dépensés et le sort se résout normalement. S'il est réussi, les effets du sort épargnent le personnage. Il n'est pas possible d'utiliser ce pouvoir après l'incantation d'un sort pour en contrer les éventuels effets, il faut le faire au moment précis du lancer du sort. On ne peut donc pas s'immuniser à la lave d'un volcan invoqué, il faut nier l'invocation.\nDans le cas d'un phénomène surnaturel durable (tempête élémentaire, geyser d'énergie), le meneur fixera lui même la Difficulté du jet, cette dernière allant de 20 à 35 selon l'effet rencontré. "),
  sondeMentale(title: "Sonde mentale", cost: 3, description: "Ce pouvoir facilite la liaison de deux esprits. Il permet d'obtenir un bonus de 3 + 1/NR sur les pouvoirs Mentaux. Ce pouvoir est le seul qui soit vaguement perceptible, sa victime ressentant une sensation de gêne non-interprétable à moins qu'elle ne possède des Pouvoirs de l'esprit (même un mage draconiste expérimenté ne l'identifiera pas). Si la cible résiste activement ou appréhende le contact (dans le cas d'un néophyte Humaniste), il convient de résoudre un jet d'Opposition de Mental+Tendance Homme contre Mental+Tendance Majeure de la cible. Ce pouvoir coûte un point de Ferveur à lancer, plus un point par trois tours de maintien."),
  telekinesie(title: "Télékinésie", cost: 5, description: "Ce pouvoir permet de déplacer des objets en les visualisant mentalement en mouvement. Ce pouvoir fonctionne à vue, sa Difficulté et son coût dépendent de la taille et de la masse de la cible.\nLa Difficulté est de 10 pour un objet de la taille d'un melon, de 15 pour un coffre, de 20 pour un animal ou un humain, et de 25 à 35 pour un cheval, un chariot ou un gros rocher.\nLe coût est d'un point de Ferveur jusqu'à 5 kg, de 2 jusqu'à 10kg, de 3 jusqu'à 25 kg, de 4 pour 50 kg, de 5 pour 100 kg, de 6 pour 500 kg et de 7 pour une tonne (le maximum).\nLes NR obtenus déterminent la vitesse relative de l'objet et influent sur ses dommages (1D10/NR dû au choc). Si l'objet est une arme, les dommages sont considérés comme infligés avec une Force de 0 (+1D10 par NR, comme d'habitude). Si l'objet est un outil, il est possible de s'en servir par un jet de Mental+Perception contre une Difficulté déterminée par le meneur (qui jugera également de la logique de l'utilisation). Il est possible de maintenir un objet en mouvement en dépensant un point de Ferveur par action consécutive au mouvement initial."),
  telepathie(title: "Télépathie", cost: 3, description: "Ce pouvoir Mental permet une communication non verbale à des distances importantes. Il est possible de faire passer des images et des souvenirs si l'on utilise conjointement le pouvoir d'Invasion mentale, sans quoi seuls les mots sont autorisés. La télépathie impose de connaître sa cible et nécessite un jet de Mental+Empathie pour établir le contact. La Difficulté est de 10 au toucher, de 15 à vue, de 20 pour 10 km, de 25 pour 100 km, de 30 pour 1000 km et de 35 à l'autre bout de Kor. Ce pouvoir dure ensuite un tour par NR obtenu sur un jet de Mental+Empathie contre 0. A la fin de cette période, il est possible de continuer la discussion en réussissant un nouveau jet dont la Difficulté est alors augmentée de 5 (cumulatif). Le coût de ce pouvoir est d'un point de Ferveur par tour et la transmission se fait à la vitesse de la parole."),
  transcendance(title: "Transcendance", cost: 6, description: "Ce pouvoir spectaculaire permet de faire le vide en soi et de se laisser guider par son inconscient. En quelque sorte, il s'agit d'une transfiguration au bénéfice de M'lan. Le personnage doit réussir un jet de Volonté+Tendance Homme contre 20 (seule la Chance est utilisable) et dépenser définitivement un point de Maîtrise. Il peut alors réussir une action héroïque que le meneur de jeu prendra soin de mettre en scène et de ne déclencher qu'à bon escient. Le personnage transcendé peut alors doubler ses NR éventuels sur le prochain jet qu'il va effectuer ou imposer un malus à l'action d'un défenseur qui s'oppose à lui (jet de parade, esquive ou d'Opposition). Ce malus est égal aux points de Ferveur que l'Humaniste choisit de dépenser. Ce pouvoir considérable oblige son utilisateur à être actif, glorieux et audacieux dans l'action entreprise."),
  transeDActivite(title: "Transe d'activité", cost: 3, description: "Ce pouvoir personnel permet de se passer de sommeil et de résister aux effets de la faim. Sauter un repas demande un jet de Mental+Résistance d'une Difficulté 10 (+3/repas déjà sauté), ainsi que la dépense de 2 points de Ferveur. Sauter une nuit de sommeil ou éviter la fatigue d'une nuit blanche demande un jet de Mental+Résistance d'une Difficulté 15 (+5/nuit déjà sautée), ainsi que la dépense de 3 points de Ferveur."),
  ;

  final String title;
  final int cost;
  final String description;

  const SpiritPower({
    required this.title,
    required this.cost,
    required this.description
  });
}