// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'character_caste.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CharacterCastePrivilege _$CharacterCastePrivilegeFromJson(
  Map<String, dynamic> json,
) => CharacterCastePrivilege(
  privilege: $enumDecode(_$CastePrivilegeEnumMap, json['privilege']),
  description: json['description'] as String?,
  selectedCost: (json['selected_cost'] as num?)?.toInt(),
);

Map<String, dynamic> _$CharacterCastePrivilegeToJson(
  CharacterCastePrivilege instance,
) => <String, dynamic>{
  'privilege': _$CastePrivilegeEnumMap[instance.privilege]!,
  'description': instance.description,
  'selected_cost': instance.selectedCost,
};

const _$CastePrivilegeEnumMap = {
  CastePrivilege.chercheur: 'chercheur',
  CastePrivilege.laForceDeLAme: 'laForceDeLAme',
  CastePrivilege.lesCerclesDuProgres: 'lesCerclesDuProgres',
  CastePrivilege.mageImperial: 'mageImperial',
  CastePrivilege.resistantDeLOmbre: 'resistantDeLOmbre',
  CastePrivilege.reseauHumaniste: 'reseauHumaniste',
  CastePrivilege.adepteMetallique: 'adepteMetallique',
  CastePrivilege.apprenti: 'apprenti',
  CastePrivilege.auraDePuissance: 'auraDePuissance',
  CastePrivilege.autorisation: 'autorisation',
  CastePrivilege.canalElementaire: 'canalElementaire',
  CastePrivilege.charteDAtelier: 'charteDAtelier',
  CastePrivilege.conscienceElementaire: 'conscienceElementaire',
  CastePrivilege.corpsDAcier: 'corpsDAcier',
  CastePrivilege.ecole: 'ecole',
  CastePrivilege.elementalisme: 'elementalisme',
  CastePrivilege.familier: 'familier',
  CastePrivilege.gardeMetallique: 'gardeMetallique',
  CastePrivilege.notable: 'notable',
  CastePrivilege.outils: 'outils',
  CastePrivilege.psychometrie: 'psychometrie',
  CastePrivilege.reparationDeRoutine: 'reparationDeRoutine',
  CastePrivilege.symbiose: 'symbiose',
  CastePrivilege.expertiseArtisan: 'expertiseArtisan',
  CastePrivilege.faveurPolitiqueArtisan: 'faveurPolitiqueArtisan',
  CastePrivilege.tuteurArtisan: 'tuteurArtisan',
  CastePrivilege.compagnonDuVoyage: 'compagnonDuVoyage',
  CastePrivilege.faussaire: 'faussaire',
  CastePrivilege.mecene: 'mecene',
  CastePrivilege.adaptation: 'adaptation',
  CastePrivilege.anticipation: 'anticipation',
  CastePrivilege.argotCombattant: 'argotCombattant',
  CastePrivilege.botteSecrete: 'botteSecrete',
  CastePrivilege.convictionSuperieure: 'convictionSuperieure',
  CastePrivilege.doubleAttaque: 'doubleAttaque',
  CastePrivilege.engagement: 'engagement',
  CastePrivilege.feinte: 'feinte',
  CastePrivilege.recuperation: 'recuperation',
  CastePrivilege.riposte: 'riposte',
  CastePrivilege.sommeilLeger: 'sommeilLeger',
  CastePrivilege.vigilanceCombattant: 'vigilanceCombattant',
  CastePrivilege.alliesMercenairesCombattant: 'alliesMercenairesCombattant',
  CastePrivilege.compagnonsDeBatailleCombattant:
      'compagnonsDeBatailleCombattant',
  CastePrivilege.maitriseDArmureCombattant: 'maitriseDArmureCombattant',
  CastePrivilege.dissimulation: 'dissimulation',
  CastePrivilege.predateurNocture: 'predateurNocture',
  CastePrivilege.bonneFoi: 'bonneFoi',
  CastePrivilege.bonneFortune: 'bonneFortune',
  CastePrivilege.expertise: 'expertise',
  CastePrivilege.faveurPolitique: 'faveurPolitique',
  CastePrivilege.fournisseurDePoisons: 'fournisseurDePoisons',
  CastePrivilege.notorieteCommercant: 'notorieteCommercant',
  CastePrivilege.paria: 'paria',
  CastePrivilege.psychologie: 'psychologie',
  CastePrivilege.reflexesDeFuite: 'reflexesDeFuite',
  CastePrivilege.reseau: 'reseau',
  CastePrivilege.ressources: 'ressources',
  CastePrivilege.rumeurs: 'rumeurs',
  CastePrivilege.surprise: 'surprise',
  CastePrivilege.connaissanceDuMondeCommercant: 'connaissanceDuMondeCommercant',
  CastePrivilege.messagerCommercant: 'messagerCommercant',
  CastePrivilege.relationsDAffairesCommercant: 'relationsDAffairesCommercant',
  CastePrivilege.laCause: 'laCause',
  CastePrivilege.majordome: 'majordome',
  CastePrivilege.petitCarnet: 'petitCarnet',
  CastePrivilege.ambassade: 'ambassade',
  CastePrivilege.aplomb: 'aplomb',
  CastePrivilege.avalDraconique: 'avalDraconique',
  CastePrivilege.calligraphieOfficielle: 'calligraphieOfficielle',
  CastePrivilege.demagogie: 'demagogie',
  CastePrivilege.ecritTechnique: 'ecritTechnique',
  CastePrivilege.garantErudit: 'garantErudit',
  CastePrivilege.illumine: 'illumine',
  CastePrivilege.linguistique: 'linguistique',
  CastePrivilege.memoire: 'memoire',
  CastePrivilege.notorieteErudit: 'notorieteErudit',
  CastePrivilege.faveurPolitiqueErudit: 'faveurPolitiqueErudit',
  CastePrivilege.messagerErudit: 'messagerErudit',
  CastePrivilege.psychologieErudit: 'psychologieErudit',
  CastePrivilege.graphologue: 'graphologue',
  CastePrivilege.reseauOcculte: 'reseauOcculte',
  CastePrivilege.anonymat: 'anonymat',
  CastePrivilege.approvisionnement: 'approvisionnement',
  CastePrivilege.aura: 'aura',
  CastePrivilege.bourreau: 'bourreau',
  CastePrivilege.cotation: 'cotation',
  CastePrivilege.detachement: 'detachement',
  CastePrivilege.duelliste: 'duelliste',
  CastePrivilege.empathieAquatique: 'empathieAquatique',
  CastePrivilege.empathieElementaire: 'empathieElementaire',
  CastePrivilege.familierMagique: 'familierMagique',
  CastePrivilege.immuniteContreLElectricite: 'immuniteContreLElectricite',
  CastePrivilege.insensibiliteALaChaleur: 'insensibiliteALaChaleur',
  CastePrivilege.intellectualisation: 'intellectualisation',
  CastePrivilege.laboratoire: 'laboratoire',
  CastePrivilege.langageTechnique: 'langageTechnique',
  CastePrivilege.leurre: 'leurre',
  CastePrivilege.maitreInstructeurDeMagie: 'maitreInstructeurDeMagie',
  CastePrivilege.maitriseDesEnergies: 'maitriseDesEnergies',
  CastePrivilege.messager: 'messager',
  CastePrivilege.messagerOnirique: 'messagerOnirique',
  CastePrivilege.mouvementDeFoule: 'mouvementDeFoule',
  CastePrivilege.nomDeKalimsshar: 'nomDeKalimsshar',
  CastePrivilege.passeur: 'passeur',
  CastePrivilege.pelerinOnirique: 'pelerinOnirique',
  CastePrivilege.pistesCachees: 'pistesCachees',
  CastePrivilege.predispositions: 'predispositions',
  CastePrivilege.prevoyance: 'prevoyance',
  CastePrivilege.privilegeDeVoyageur: 'privilegeDeVoyageur',
  CastePrivilege.protectionDesEeries: 'protectionDesEeries',
  CastePrivilege.puissanceDeSang: 'puissanceDeSang',
  CastePrivilege.puissanceElementaire: 'puissanceElementaire',
  CastePrivilege.refugeSylvestre: 'refugeSylvestre',
  CastePrivilege.renommee: 'renommee',
  CastePrivilege.sacrificeElementaire: 'sacrificeElementaire',
  CastePrivilege.sensDeLEther: 'sensDeLEther',
  CastePrivilege.siphonElementaire: 'siphonElementaire',
  CastePrivilege.sortilegeFetiche: 'sortilegeFetiche',
  CastePrivilege.sortilegeFeticheCites: 'sortilegeFeticheCites',
  CastePrivilege.sortilegeFeticheFeu: 'sortilegeFeticheFeu',
  CastePrivilege.sortilegeFeticheMetal: 'sortilegeFeticheMetal',
  CastePrivilege.sortilegeFeticheNature: 'sortilegeFeticheNature',
  CastePrivilege.sortilegeFeticheOceans: 'sortilegeFeticheOceans',
  CastePrivilege.sortilegeFeticheOmbre: 'sortilegeFeticheOmbre',
  CastePrivilege.sortilegeFetichePierre: 'sortilegeFetichePierre',
  CastePrivilege.sortilegeFeticheReves: 'sortilegeFeticheReves',
  CastePrivilege.sortilegeFeticheVents: 'sortilegeFeticheVents',
  CastePrivilege.style: 'style',
  CastePrivilege.transmutation: 'transmutation',
  CastePrivilege.tuteur: 'tuteur',
  CastePrivilege.tuteurSpecialise: 'tuteurSpecialise',
  CastePrivilege.visions: 'visions',
  CastePrivilege.visionDeLaTrame: 'visionDeLaTrame',
  CastePrivilege.voixDeKalimsshar: 'voixDeKalimsshar',
  CastePrivilege.autoriteMagePierre: 'autoriteMagePierre',
  CastePrivilege.apprentiMage: 'apprentiMage',
  CastePrivilege.engagementMage: 'engagementMage',
  CastePrivilege.memoireMage: 'memoireMage',
  CastePrivilege.porteParoleMage: 'porteParoleMage',
  CastePrivilege.discretion: 'discretion',
  CastePrivilege.emotionsExacerbees: 'emotionsExacerbees',
  CastePrivilege.espritEsclave: 'espritEsclave',
  CastePrivilege.reveur: 'reveur',
  CastePrivilege.donDeBrorne: 'donDeBrorne',
  CastePrivilege.donDeHeyra: 'donDeHeyra',
  CastePrivilege.donDeKali: 'donDeKali',
  CastePrivilege.donDeKalimsshar: 'donDeKalimsshar',
  CastePrivilege.donDeKezyr: 'donDeKezyr',
  CastePrivilege.donDeKhy: 'donDeKhy',
  CastePrivilege.donDeKhymera: 'donDeKhymera',
  CastePrivilege.donDeKroryn: 'donDeKroryn',
  CastePrivilege.donDeMoryagorn: 'donDeMoryagorn',
  CastePrivilege.donDeNenya: 'donDeNenya',
  CastePrivilege.donDOzyr: 'donDOzyr',
  CastePrivilege.donDeSolyr: 'donDeSolyr',
  CastePrivilege.donDeSzyl: 'donDeSzyl',
  CastePrivilege.empathieVegetaleMineure: 'empathieVegetaleMineure',
  CastePrivilege.empathieVegetaleMajeure: 'empathieVegetaleMajeure',
  CastePrivilege.empathieAnimaleMineure: 'empathieAnimaleMineure',
  CastePrivilege.empathieAnimaleMajeure: 'empathieAnimaleMajeure',
  CastePrivilege.empathieDraconique: 'empathieDraconique',
  CastePrivilege.empathieMinerale: 'empathieMinerale',
  CastePrivilege.empathieAquatiqueProdige: 'empathieAquatiqueProdige',
  CastePrivilege.eruptionNaturelle: 'eruptionNaturelle',
  CastePrivilege.empathieClimatique: 'empathieClimatique',
  CastePrivilege.aplombProdige: 'aplombProdige',
  CastePrivilege.engagementProdige: 'engagementProdige',
  CastePrivilege.reflexesDeDegagement: 'reflexesDeDegagement',
  CastePrivilege.adopte: 'adopte',
  CastePrivilege.autorite: 'autorite',
  CastePrivilege.cuirasse: 'cuirasse',
  CastePrivilege.defense: 'defense',
  CastePrivilege.influences: 'influences',
  CastePrivilege.lucidite: 'lucidite',
  CastePrivilege.porteParole: 'porteParole',
  CastePrivilege.regardInquisiteur: 'regardInquisiteur',
  CastePrivilege.renseignement: 'renseignement',
  CastePrivilege.requisition: 'requisition',
  CastePrivilege.suspicion: 'suspicion',
  CastePrivilege.signesDeBatailleProtecteur: 'signesDeBatailleProtecteur',
  CastePrivilege.engagementProtecteur: 'engagementProtecteur',
  CastePrivilege.notorieteProtecteur: 'notorieteProtecteur',
  CastePrivilege.apparenceDraconique: 'apparenceDraconique',
  CastePrivilege.crocsDraconiques: 'crocsDraconiques',
  CastePrivilege.ailes: 'ailes',
  CastePrivilege.cuirasseDraconique: 'cuirasseDraconique',
  CastePrivilege.reflexesSuperieurs: 'reflexesSuperieurs',
  CastePrivilege.savoirAncestral: 'savoirAncestral',
  CastePrivilege.harmonieMagique: 'harmonieMagique',
  CastePrivilege.resistanceMinerale: 'resistanceMinerale',
  CastePrivilege.sensSuperieur: 'sensSuperieur',
  CastePrivilege.instructionDraconique: 'instructionDraconique',
  CastePrivilege.conviction: 'conviction',
  CastePrivilege.sacrifice: 'sacrifice',
  CastePrivilege.archer: 'archer',
  CastePrivilege.chasseur: 'chasseur',
  CastePrivilege.compagnons: 'compagnons',
  CastePrivilege.connaissanceDuMonde: 'connaissanceDuMonde',
  CastePrivilege.enigmatique: 'enigmatique',
  CastePrivilege.filsDeLaTerre: 'filsDeLaTerre',
  CastePrivilege.garantVoyageur: 'garantVoyageur',
  CastePrivilege.logistique: 'logistique',
  CastePrivilege.maitriseDArmure: 'maitriseDArmure',
  CastePrivilege.rancune: 'rancune',
  CastePrivilege.solitaire: 'solitaire',
  CastePrivilege.vigilanceVoyageur: 'vigilanceVoyageur',
  CastePrivilege.ambassadeVoyageur: 'ambassadeVoyageur',
  CastePrivilege.familierVoyageur: 'familierVoyageur',
  CastePrivilege.linguistiqueVoyageur: 'linguistiqueVoyageur',
  CastePrivilege.compagnonDeShar: 'compagnonDeShar',
  CastePrivilege.pionnier: 'pionnier',
  CastePrivilege.souterrain: 'souterrain',
};

CharacterCaste _$CharacterCasteFromJson(Map<String, dynamic> json) =>
    CharacterCaste(
      caste: $enumDecode(_$CasteEnumMap, json['caste']),
      status: $enumDecode(_$CasteStatusEnumMap, json['status']),
      career: $enumDecodeNullable(_$CareerEnumMap, json['career']),
    );

Map<String, dynamic> _$CharacterCasteToJson(CharacterCaste instance) =>
    <String, dynamic>{
      'caste': _$CasteEnumMap[instance.caste]!,
      'status': _$CasteStatusEnumMap[instance.status]!,
      'career': _$CareerEnumMap[instance.career],
    };

const _$CasteEnumMap = {
  Caste.sansCaste: 'sansCaste',
  Caste.artisan: 'artisan',
  Caste.artisanNoir: 'artisanNoir',
  Caste.combattant: 'combattant',
  Caste.combattantNoir: 'combattantNoir',
  Caste.commercant: 'commercant',
  Caste.commercantNoir: 'commercantNoir',
  Caste.erudit: 'erudit',
  Caste.eruditNoir: 'eruditNoir',
  Caste.mage: 'mage',
  Caste.mageNoir: 'mageNoir',
  Caste.prodige: 'prodige',
  Caste.protecteur: 'protecteur',
  Caste.protecteurNoir: 'protecteurNoir',
  Caste.voyageur: 'voyageur',
  Caste.voyageurFataliste: 'voyageurFataliste',
};

const _$CasteStatusEnumMap = {
  CasteStatus.none: 'none',
  CasteStatus.apprenti: 'apprenti',
  CasteStatus.initie: 'initie',
  CasteStatus.expert: 'expert',
  CasteStatus.maitre: 'maitre',
  CasteStatus.grandMaitre: 'grandMaitre',
};

const _$CareerEnumMap = {
  Career.alchimiste: 'alchimiste',
  Career.architecte: 'architecte',
  Career.artisanElementaire: 'artisanElementaire',
  Career.forgeron: 'forgeron',
  Career.gardeMetallique: 'gardeMetallique',
  Career.mecaniste: 'mecaniste',
  Career.mineur: 'mineur',
  Career.orfevre: 'orfevre',
  Career.tisserand: 'tisserand',
  Career.aventurier: 'aventurier',
  Career.chevalier: 'chevalier',
  Career.duelliste: 'duelliste',
  Career.gladiateur: 'gladiateur',
  Career.guerrier: 'guerrier',
  Career.lutteur: 'lutteur',
  Career.maitreDArmes: 'maitreDArmes',
  Career.mercenaire: 'mercenaire',
  Career.paladin: 'paladin',
  Career.strategeCombattant: 'strategeCombattant',
  Career.courtisane: 'courtisane',
  Career.diplomate: 'diplomate',
  Career.espion: 'espion',
  Career.joueur: 'joueur',
  Career.marchand: 'marchand',
  Career.marchandItinerant: 'marchandItinerant',
  Career.mendiant: 'mendiant',
  Career.tenancier: 'tenancier',
  Career.voleur: 'voleur',
  Career.architectes: 'architectes',
  Career.astronomes: 'astronomes',
  Career.cartographes: 'cartographes',
  Career.conteurs: 'conteurs',
  Career.erudits: 'erudits',
  Career.herboristes: 'herboristes',
  Career.historiens: 'historiens',
  Career.medecins: 'medecins',
  Career.navigateurs: 'navigateurs',
  Career.scientifiques: 'scientifiques',
  Career.conjurateur: 'conjurateur',
  Career.enchanteur: 'enchanteur',
  Career.fideleDeChimere: 'fideleDeChimere',
  Career.gardienMage: 'gardienMage',
  Career.generaliste: 'generaliste',
  Career.guerisseurMage: 'guerisseurMage',
  Career.invocateur: 'invocateur',
  Career.mageDeCombat: 'mageDeCombat',
  Career.necromant: 'necromant',
  Career.profanateur: 'profanateur',
  Career.questeurBlanc: 'questeurBlanc',
  Career.reveur: 'reveur',
  Career.specialisteDesRituels: 'specialisteDesRituels',
  Career.specialisteElementaire: 'specialisteElementaire',
  Career.tueurDeReves: 'tueurDeReves',
  Career.gardienProdige: 'gardienProdige',
  Career.ceuxQuiNeFontQuUn: 'ceuxQuiNeFontQuUn',
  Career.fervent: 'fervent',
  Career.guerisseurProdige: 'guerisseurProdige',
  Career.mediateur: 'mediateur',
  Career.missionnaire: 'missionnaire',
  Career.poeteDeLaNature: 'poeteDeLaNature',
  Career.prodigeAnimal: 'prodigeAnimal',
  Career.prophete: 'prophete',
  Career.sage: 'sage',
  Career.tuteur: 'tuteur',
  Career.gardeDuCorps: 'gardeDuCorps',
  Career.hommeDragon: 'hommeDragon',
  Career.ingenieurMilitaire: 'ingenieurMilitaire',
  Career.inquisiteur: 'inquisiteur',
  Career.instructeur: 'instructeur',
  Career.legionnaire: 'legionnaire',
  Career.milicien: 'milicien',
  Career.protecteurItinerant: 'protecteurItinerant',
  Career.soldat: 'soldat',
  Career.strategeProtecteur: 'strategeProtecteur',
  Career.chasseurs: 'chasseurs',
  Career.eclaireurs: 'eclaireurs',
  Career.errants: 'errants',
  Career.explorateurs: 'explorateurs',
  Career.menestrels: 'menestrels',
  Career.messagers: 'messagers',
  Career.missionnaires: 'missionnaires',
};
